pyscript/pyscript

pyscriptjs/examples/fractals.py
pyscriptjs/examples/numpy_canvas_fractals.html

Adds a configurable Newton's fractal and allows for interactive zoom with mouse gestures. Inputs are:
* a polynomial in `z` (parsed by SymPy)
* a coefficient
* X/Y ranges (use mouse to zoom an area)
* convergence - color maps by which root each pixel converged to (red indicates no convergence in 100 iterations)
* iterations - color maps by the number iterations required to converge (the same as Mandelbrot and Julia)

Improvements to `numpy_canvas_fractals` example

---

pyscriptjs/src/components/pybox.ts

When running npm build you get the following error, casting ChildNode as HTMLElement will fix:
```
!) Plugin typescript: @rollup/plugin-typescript TS2345: Argument of type 'ChildNode' is not assignable to parameter of type 'HTMLElement'.
Type 'ChildNode' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 223 more.
src/components/pybox.ts: (57:24)
57             addClasses(node, [width, 'mx-1'])
~~~~
```

Fixing typescript error in build process

---

pyscriptjs/examples/pylist.py
pyscriptjs/examples/repl2.html
pyscriptjs/examples/simple_clock.html
pyscriptjs/examples/todo-pylist.html
pyscriptjs/src/components/base.ts

This replaces using the interpreter promise with using the interpreter itself. Also make it event base instead of relying on delays. This is not a global fix and we still need to fix elsewhere but the rest can come in a follow up PR

Hotfix for py-script/py-repl loading 

---

pyscriptjs/src/utils.ts

Runs `ltrim` before HTML decoding the string. The HTMl decode strips the indentation of the first line and thereby caused `ltrim` to be a no-op.
Fixes https://github.com/pyscript/pyscript/issues/104

Fix dedenting of <py-script> code

---

README.md

I couldn't find where the `examples` folder was. I think it might be worth to have the full path to it on the README.
Thanks for the project!

[MINOR] Add full path to examples on README

---

pyscriptjs/src/interpreter.ts
pyscriptjs/src/pyscript.py

The problem here was that it was calling `type.__repr__` which is missing the self argument. Instead we should simply call `repr(type)`. There is however a secondary problem, which is that since we are rendering straight to the DOM the `<` and `>` in the type repr get taken as an HTML tag and we still don't get any output. We will have to consider whether to always escape `<` and `>` when rendered into the DOM which would unfortunately mean that we cannot have strings be directly interpreted as HTML (e.g. breaking @pzwang's rick-roll demo in the PyCon keynote).
Partially Fixes https://github.com/pyscript/pyscript/issues/120

Handle __repr__ of types

---

pyscriptjs/src/components/pyenv.ts

Fix misspelled logs "enviroment" -> "environment" in pyenv.ts 
close #200

fix misspelled logs

---

pyscriptjs/src/interpreter.ts

distutils is a deprecated and quite large (around to 1MB) stdlib module that would be removed in Python 3.12 . 
Most users likely don't need it, and if they do, they can add it explicitly as a dependency in py-env. 
This PR disables loading it by default. Though maybe it would be good to wait until examples are tested #152 before merging this, just in case.

Don't load distutils in the Python standard library

---

pyscriptjs/examples/index.html

This PR gives some more credits to the libraries used in the examples by adding a link to their website. This is how the links look like, they have the same color as the example link.

Add links to the libraries used in the examples

---

.pre-commit-config.yaml
pyscriptjs/examples/micrograd_ai.py

In order to prevent conflicts between `black` and `isort`, we need to set the `--profile black` arguments to `isort` in the `pre-commit` configuration.

Use black profile in isort to prevent conflicts

---

pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/src/components/pyenv.ts

Hi,
This PR contains the following changes to fix some ESLint warnings of `PyEnv`:
- Install js-yaml type definition
- Use `unknown` instead of `any` and add type guards

Improve type annotations

---

pyscriptjs/src/pyscript.py

Currently any html block, which ideally should be indented properly to enhance readability, cannot be written as is. Adding `textwrap.dedent` helps with this and allows one to write indented html blocks as strings and later properly render the html when it is generated.
**Example**
https://github.com/pyscript/pyscript/blob/22ffbcb21dbfe62108d51339538b73f812eeb39c/pyscriptjs/src/pyscript.py#L254-L265
The update (via this PR) makes the following work.
https://github.com/sugatoray/pyscript/blob/1f076e76df426a90ed186e5d21dc0d3361c91a43/pyscriptjs/src/pyscript.py#L261-L266

Adding `textwrap.dedent` for allowing indented html blocks

---

pyscriptjs/rollup.config.js

Hi,
This PR updates Rollup config to fix the following warning:
```
(!) Plugin typescript: @rollup/plugin-typescript: Rollup 'sourcemap' option must be set to generate source maps.
```

Update Rollup config

---

pyscriptjs/src/interpreter.ts

Hi,
This PR changes deprecated `substr()` to `substring()`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

Avoid using a deprecated method

---

pyscriptjs/examples/todo.html
pyscriptjs/rollup.config.js
pyscriptjs/src/components/base.ts

#395 was a temporary fix but this should be the real fix that closes #370 and other issues reporting errors with `querySelector` selecting elements starting with a `-[1-9]` value. This fixes the underlying issue. 
We were using this.constructor.name that doesn't seem to work well with the current config of `terser`. Independently of that, the goal here was to generate a meaningful unique id. We can do that with just the static string (at least I can't come up with really strong reasons for having the id to change based on the class name, besides personal taste for semantics).

fix autogenerated element

---

pyscriptjs/src/components/base.ts
pyscriptjs/src/components/pyscript.ts

original version shows the error at #stdout element, not #stderr 
```
<h2>stdout</h2>
<pre id="stdout"></pre>
<h2>stderr</h2>
<pre id="stderr"></pre>
<py-script std-out="stdout" std-err="stderr">
error.is.occurred()
</py-script>
```

fixed the bug std-err attribute cannot set stderr elements properly

---

pyscriptjs/src/components/base.ts
pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/utils.ts

Hey,
I think the play button in the REPL component was misaligned. My commit changes its position from
to
Was the initial alignment intended?
EDIT:
Fixed the auto-generate behavior to correctly remove the auto-generate attribute from generated children. Also added functionality to get the last exec-id and add to that, instead of the root elements exec-id.

fixed REPL bugs

---

docs/tutorials/getting-started.md

Fixes #415 
@idanenglander I've also added `<py-config>`. Not sure if it belongs to getting-started to may be more somewhere "more advanced" but thought it'd be good to add the content and let you figure out the best placement. :)

add components description in getting started

---

docs/tutorials/getting-started.md

- place holders => placeholders
- can by used by => can be used by

Fix typo in getting-started.md

---

pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/rollup.config.js
pyscriptjs/src/interpreter.ts

Hi,
This PR updates Rollup config to bundle the Python files into the output file. This makes that the interpreter can load the Python logic directly.
Links:
- https://github.com/pyscript/pyscript/pull/207
- https://github.com/TrySound/rollup-plugin-string

Bundle the Python files into the output file

---

pyscriptjs/src/components/base.ts
pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/pyscript.py

Hey,
after working over my last PR, I now have a new proposal on handling output with py-repl.
Currently, the output gets stacked/appended to the output element. That does not seem like the expected behavior.
My PR proposes the `output-append` attribute to the REPL. The PR changes the default behavior of the REPL to replace its output with every execution. If `output-append` is set on the py-repl tag, the output is appended as before.
Here is a GIF of the new behavior:
**Important note:** As the pyscript.py and base.ts files are modified for this to work, these changes need to be tested with other components/use cases.
Any feedback and discussion on how to do better are highly welcome, thanks!
Kind regards
Mariano

[PROPOSAL] REPL output replacement

---

docs/tutorials/getting-started.md

Hi maintainers!
I went through the Getting Started doc and found a little typo there. In the  **py-config tag** section, the  **lang** field in the runtime value was listed as **name**. I found this as a typo and decided to send a PR to fix this. I hope it gets merged; thanks :) 
I would love the feedback of the maintainers on this; cheers!

Fixed typo in getting-started.md

---

docs/tutorials/getting-started.md
examples/simple_clock.html
pyscriptjs/src/components/pyconfig.ts

Hi,
This PR changes the metadata format written in `<py-config>` tag.
The current metadata format is like this:
```yaml
- autoclose_loader: false
- runtimes:
-
src: "https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js"
name: pyodide-0.20
lang: python
```
Representing it as JSON is like this:
```json
[
{
"autoclose_loader": false
},
{
"runtimes": [
{
"src": "https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js",
"name": "pyodide-0.20",
"lang": "python"
}
]
}
]
```
I think this should be like this:
```yaml
autoclose_loader: false
runtimes:
- src: "https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js"
name: pyodide-0.20
lang: python
```
Representing it as JSON is like this:
```json
{
"autoclose_loader": false,
"runtimes": [
{
"src": …
```

Change the metadata format

---

docs/tutorials/getting-started.md

The "the py-config tag" options list contains a few typos (and could be a bit easier on the eyes).
This commit:
* Changes "name" to "lang".
* Changes "to provide clarify" to "for clarity".
* Reformats the options list it as a table, which is easier to read.
Also, for some context:
This is a case of "Baby's First Open-Source Pull Request" so feel free to educate me as to how these changes could ruin everything or why they aren't desired. I will take no offense. Cheers!

Fix typo/reformat  `GETTING-STARTED.md`

---

pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/components/pyscript.ts

Reads in code for `<py-repl>` and `<py-script>` and replaces `&lt;` and `&gt;` by `<` and `>`.
Fix bug #480

fix: < and > are parsed with HTML escape symbols

---

examples/simple_clock.html

The old version of the simple_clock.html example erroneously referenced "./build/" instead of "https://pyscript.net/alpha/" in its reference to PyScript CSS and JavaScript resources. Fixes: #495.

Fix URL source reference in examples/simple_clock.html

---

.github/workflows/build-release.yml
.github/workflows/docs-release.yml
.github/workflows/publish-release.yml

This process for now will:
1. Test and build artifacts on a tag. Tags can be any commit, HEAD or cherry-picked.
2. Create a draft release with change notes and contributors generated from PR activity
3. At this point a maintainer can review the draft and add their own notes about features, breaking changes, etc.
4. Once the release is published, the artifacts will be built and tested again, and if tests pass pushed to S3 in two locations (one to maintain legacy file location).
Note: Building/testing before and after release publication is slightly redundant but since there's a manual break in the workflow, it will be required until we find a way to cache the artifact (if that's preferred). Since we're using the same ref/tag in any case, we should be able to trust that the builds are …

Release automation

---

pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/src/components/base.ts
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/interpreter.ts
pyscriptjs/src/pyodide.ts

Hi,
This PR changes to use the type definition of pyodide instead of the our own.
Note: The latest release of pyodide doesn't export `PyodideInterface` type, so I added a workaround to get it. Maybe the next release resolves that.

Use the type definition of pyodide

---

.github/workflows/docs-review.yml

Previous if: statement didn't appear to work. This will check that the repo owner is pyscript, which will naturally exclude any forks.
See here for forked runs still happening:
https://github.com/pyscript/pyscript/actions/workflows/docs-review.yml

Try new method to keep CI from running on forks

---

examples/handtrack/say_hello.html
examples/mario/play_mario.html

typos in 
- play_mario.html: `../` in link href which causes error, `sstart` typo
- handtrack/say_hello.html: `../` in link href which causes error

fix: typos in play_mario, handtrack examples

---

CONTRIBUTING.md
TROUBLESHOOTING.md

I expanded upon the contribution docs (mostly the `setting up environment` section) as well as fixing some formatting (mostly in the titles). I also added the `troubleshooting.md` page for common troubleshooting problems throughout PyScript.

Clearer contribution docs & add troubleshooting page

---

pyscriptjs/src/components/base.ts

We smh let this pass on dc84d7c1b5c6816f350cbfffbd6a019c03ad23a2
`xPyWidget` should be updated every time we create a custom widget :)

Re-introduce xPyWidget update on CustomWidget's class

---

.pre-commit-config.yaml
pyscriptjs/tests/test_examples.py

In this PR I'll start adding tests that don't just check whether examples are rendering but actually verifies correct behavior.
Note: I disabled bandit 101 checks (`Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.`) because checking for asserts is pretty silly in general (imo) but since pytest is entirely based around the use of asserts it makes no sense to enforce.
Tests added:

Add tests verifying correct example behavior

---

pyscriptjs/Makefile
pyscriptjs/environment.yml

This helps us with installation issues on an M1 mac on running `make setup`

use pip (latest) to install playwright

---

pyscriptjs/src/stores.ts

Hi,
This PR adds a type annotation to resolve the following compile error:
```console
$ npx tsc --noEmit
src/components/base.ts:9:5 - error TS2740: Type '{}' is missing the following properties from type 'PyodideInterface': globals, FS, pyodide_py, version, and 16 more.
9     runtime = value;
~~~~~~~
src/components/base.ts:193:37 - error TS2361: The right-hand side of an 'in' expression must not be a primitive.
193             if ('runPythonAsync' in value) {
~~~~~
src/components/base.ts:237:41 - error TS2361: The right-hand side of an 'in' expression must not be a primitive.
237                 if ('runPythonAsync' in value) {
~~~~~
src/components/base.ts:238:21 - error TS2322: Type 'unknown' is not assignable to type 'PyodideInterface'.
238                     runtime = value;
~~~~~~~ …
```

Specify the type of store value

---

pyscriptjs/src/components/pybox.ts

Hi,
this PR adds a type annotation to resolve the following ESLint warning:
```console
$ npx eslint src/components/pybox.ts
/***/pyscript/pyscriptjs/src/components/pybox.ts
54:13  warning  Unsafe assignment of type any[] to a variable of type string[]  @typescript-eslint/no-unsafe-assignment
✖ 1 problem (0 errors, 1 warning)
```

Specify the array type

---

pyscriptjs/src/styles/pyscript_base.css

PyItemTemplate.strike() uses the CSS class line-through, which was part of Tailwind. Reintroduce it in our custom CSS. This fixes the todo-pylist example

Fix the CSS of the todo-pylist example

---

pyscriptjs/src/components/pyscript.ts

Hi,
This PR removes unnecessary `await` operators to resolve the following ESLint errors:
```console
$ npx eslint src/components/pyscript.ts | grep await-thenable
214:21  error    Unexpected `await` of a non-Promise (non-"Thenable") value                                                      @typescript-eslint/await-thenable
255:21  error    Unexpected `await` of a non-Promise (non-"Thenable") value                                                      @typescript-eslint/await-thenable
```

Remove unnecessary `await`

---

pyscriptjs/src/utils.ts
pyscriptjs/tests/test_01_basic.py

Without escaping angle brackets (`<` and `>`) the DOMParser will strip out anything that looks like an HTML tag.

Ensure that angle brackets in pyscript tag are escaped before parsing

---

pyscriptjs/src/components/base.ts

This is just a small change to instantiate importmaps as an empty array so when we try to iterate over importmaps, if we didn't push any imports it will just skip the step
Also, just wanted to check, are we missing an `await` here since `_register_esm` is an async method?
https://github.com/pyscript/pyscript/blob/fa7a97ca3087d9f5c0a1fe2787a57201a33a6dce/pyscriptjs/src/components/base.ts#L124
Fixes: #707

Fix: Importmaps can be undefined

---

pyscriptjs/tests/integration/test_py_box.py
pyscriptjs/tests/integration/test_py_inputbox.py
pyscriptjs/tests/integration/test_py_repl.py
pyscriptjs/tests/integration/test_py_title.py
pyscriptjs/tests/integration/test_zz_examples.py

This PR is part of the Epic effort to increase test coverage (#679), it also helped me understand the code base a bit more :smile: 
I had to mark some tests as xfail due to #673 and #707. My approach for writing this tests was mostly to check if elements are on the page and then do some actions and confirm the output. Would this be a good way to test the components or would you like me to change anything?
The repl tests have a bit of duplicated testing (one for the component itself and one for the example), but maybe that's okay? :thinking:

Add more integration tests for py-components and examples

---

pyscriptjs/tsconfig.json

While looking at the code I've noticed that we are setting `es2016` in the tsconfig. Updating it to use `es2017` seems to have "fixed" the warning.
Fixes: #703

Fix: ObjectConstructor missing 'entries' property error

---

pyscriptjs/src/components/pybutton.ts
pyscriptjs/src/components/pyconfig.ts
pyscriptjs/src/components/pyinputbox.ts
pyscriptjs/src/components/pyloader.ts
pyscriptjs/src/components/pytitle.ts

Hi,
This PR removes overwriting properties to resolve the following TS compile errors:
```console
$ npx tsc --noEmit
src/components/pybutton.ts:5:5 - error TS2612: Property 'shadow' will overwrite the base property in 'BaseEvalElement'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
5     shadow: ShadowRoot;
~~~~~~
src/components/pybutton.ts:6:5 - error TS2612: Property 'wrapper' will overwrite the base property in 'BaseEvalElement'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
6     wrapper: HTMLElement;
~~~~~~~
src/components/pybutton.ts:7:5 - error TS2612: Property 'theme' will overwrite the base property in 'BaseEvalElement'. If this is …
```

Remove overwriting properties

---

pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/rollup.config.js

This PR attempts to fix the issue where the examples don't load the script from the build folder since we serve directly from 'examples'. 
It adds a new plugin, `rollup-plugin-copy` to the library to copy the contents from build to examples/build. I've noticed that a few packages in the `package-lock.json` lost the `"dev": true` flag. Is this a problem? Also, should the copy plugin be a dev-only dependency? :thinking: 
I've thought about three approaches:
- In the Makefile add `make build` and then copy the build folder to the examples folder
- Add a new output destination to build into `examples`
- Copy the build folder into examples on every `npm run dev`
The last approach seemed the best option since we can add a check only to do this step if we are running a non-prod build. The first …

Fix: Examples not importing pyscript from build folder when running locally

---

.gitignore
pyscriptjs/tests/integration/test_zz_examples.py
pyscriptjs/tests/unit/base.test.ts
pyscriptjs/tests/unit/pybutton.test.ts

This PR is part of the effort to increase test coverage (#679). Two new test files were added:
- one for PyButton
- one for BaseEvalElement
I wonder if this is the right approach to testing each component and perhaps some internals. Many of these tests are just asserting default behaviours and checking that things changed as we expect when calling functions.
Please let me know if you would prefer to test these differently or if you think it's good then I'll keep writing tests for the other files 😄

Add more unit tests for PyButton and BaseEvalElement

---

pyscriptjs/Makefile
pyscriptjs/src/components/base.ts
pyscriptjs/src/components/pybox.ts
pyscriptjs/src/components/pybutton.ts
pyscriptjs/src/components/pyconfig.ts
pyscriptjs/src/components/pyenv.ts
pyscriptjs/src/components/pyinputbox.ts
pyscriptjs/src/components/pyloader.ts
pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/logger.ts
pyscriptjs/src/main.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/src/python/pyscript.py
pyscriptjs/src/runtime.ts
pyscriptjs/src/stores.ts
pyscriptjs/tests/integration/support.py
pyscriptjs/tests/integration/test_01_basic.py
pyscriptjs/tests/integration/test_py_button.py
pyscriptjs/tests/integration/test_py_inputbox.py
pyscriptjs/tests/integration/test_py_runtime_config.py
pyscriptjs/tests/integration/test_zz_examples.py
pyscriptjs/tests/unit/logger.test.ts

This PR tries to improve and rationalize what we log. Key points:
- introduce `logger.ts`: each file/component is encouraged to use the logger instead of writing directly to `console.*`
* the logger automatically prepend a prefix like `[py-config]`, `[py-env]` which make it easier to understand where a certain message is printed from
* it provide a central place where to add more features in the future. E.g., I can imagine having a config setting to completely silence the logs (not implemented yet)
- use the new loggers everywhere
- write to `.info()` instead of `.log()`. The idea is to keep `console.log` free, so that for the users it's easier to tell apart their own messages and the pyscript ones
- generally improve what we log. This is an endless exercise, but I tried to print more …

Improve JS logging

---

.github/workflows/build-unstable.yml
.github/workflows/docs-latest.yml
.github/workflows/docs-release.yml
.github/workflows/docs-review.yml
.github/workflows/publish-release.yml
.github/workflows/sync-examples.yml

Saw some actions failing on aws credential helper. The syntax was odd as it lacked space around the secret value.
`${{secrets.AWS_REGION}}` vs `${{ secrets.AWS_REGION }}`

Add space before/after secrets value

---

docs/concepts/what-is-pyscript.md

As per #565 the current best fix is to simply remove the line numbers from the output

Remove line numbers from example

---

pyscriptjs/src/components/elements.ts
pyscriptjs/src/main.ts
pyscriptjs/src/runtime.ts
pyscriptjs/tests/integration/support.py
pyscriptjs/tests/integration/test_py_button.py
pyscriptjs/tests/integration/test_py_inputbox.py
pyscriptjs/tests/integration/test_py_repl.py
pyscriptjs/tests/integration/test_zz_examples.py

This PR fixes a few things:
- the 'in undefined' error that we have seen when running tests
- the flakiness of the reply tests
- the test_panel_stream tests (cannot read  properties of undefined)
- wait a short time to allow the loaded script to be inserted into head
Hopefully, you don't mind this wall of text, explaining the reasoning behind the decisions in the PR :smile:
After adding a bunch of `console.traces` I've noticed that `runAfterRuntimeInitialized` was being called from `main.js` which was a bit odd, following the code path, it seems that it was being run when we were creating the py-button custom element in `const xPyButton = customElements.define('py-button', PyButton);`  See the console output for a better visual.
<details>
<summary>Console output with traces </summary>
``` …
```

Don't create custom elements in main and fix various small issues on tests

---

pyscriptjs/Makefile

Fixed Makefile to always clean and recopy the examples build folder (located under examples). Fixes #688

Fixed Makefile to always clean and recopy the examples build folder (located under examples)

---

.github/workflows/publish-snapshot.yml
.github/workflows/snapshot.yml

A Github Actions workflow that publishes a snapshot release of `/unstable/` into `/snapshots/{name}/`. 
This is a manual workflow and is executed within the github account.
This version will test the output using AWS CLI `--dryrun` setting.
We will remov the `--dryrun` setting once we see correct behavior

Snapshot releases

---

.github/workflows/publish-snapshot.yml

Testing the `--dryrun` version produced this output and looks to be accurate. This PR removes `--dryrun` to enable the workflow.
Output with `--dryrun` testing on path `2022.09.1.RC1`

Enable "Publish Snapshot" by removing --dryrun setting

---

pyscriptjs/src/utils.ts
pyscriptjs/tests/unit/pyconfig.test.ts

The `<py-config>` default runtime schema should be minimal and not contain defaults that are not valid. All these default config properties are optional and can be overwritten by using `<py-config>`
PR process:
1. Change the default config within utils.ts to only what is necessary
2. Test all examples for correct behavior
3. Fix failing tests isolated where default values were being tested that are now undefined.
4. All tests are passing... units, ts, integration tests.
This looks and feels good to go.

Minimum viable py-config default schema

---

pyscriptjs/src/python/pyscript.py

This simplifies the logging output of OutputCtxManager with 1 console.info per message vs 2.
This is for release 2022.09.1 and we can reenable afterwards

simplify OutputCtxManager logging

---

pyscriptjs/package.json

This allows us to run the TypeScript compiler directly. Rollup runs this same command within `rollup -c` but we are not seeing the real warnings through `rollup`. Just a pair of 👓 for the codebase. 
Run tsc: `npm run tsc`

Add tsc as an optional build step with --noEmit

---

.github/stale.yaml

This adds ["Github Stale"](https://github.com/marketplace/stale) support to `pyscript/pyscript` repo with a base configuration within this PR.
A staler proactively labels and expires issues/prs/branches where no activity exists.
- Number of days of inactivity before an issue becomes stale: 60
- Number of days of inactivity before a stale issue is closed: 7
- Issues with these labels will never be considered stale: [ 'pinned', 'security' ]
- Label to use when marking an issue as stale: stale
- Comment to post when marking an issue as stale. 
```text
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
```
- Comment to post when closing a stale issue. 
```text
This issue …
```

Add Github Stale to PyScript repo

---

pyscriptjs/src/main.ts
pyscriptjs/src/utils.ts
pyscriptjs/tests/integration/test_py_config.py

Detect the case in which multiple <py-config> are listed.
Ideally I would like it to be a fatal error, but it's too hard to do it with the current state of the code, will refactor it later.
Screenshot of `test_multiple_py_config`:

Detect multiple <py-config>

---

pyscriptjs/package-lock.json
pyscriptjs/package.json

Removes `@fortawesome/free-solid-svg-icons` from the dependencies - as far as I can tell, it isn't used anywhere.
From the reference to it in #1, I think this has been around from the beginning of this repo, and just went unused at some point.
There's no savings on the shipped-bundle size since we weren't using it, but still, no reason to install it if we don't need it.

Remove fortawesome/free-solid-svg-icons

---

pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/main.ts
pyscriptjs/src/runtime.ts
pyscriptjs/src/stores.ts
pyscriptjs/tests/integration/support.py
pyscriptjs/tests/integration/test_py_config.py
pyscriptjs/tests/unit/runtime.test.ts

This is a follow-up of PR #806 and it's a big step forward towards solving issue #763.
The basic idea is that at this stage I want to streamline the execution logic and make it as linear and easy to read/understand as possible. Once we have a better understanding of what's going on, we can think of slicing it again in forms of plugins or similar, if we want.
The diff is relatively big, but for the most part is just "shuffling code around". The biggest outcome is that now the majority of the execution logic of the page follows a very linear logic, which I describe in a comment at the beginning of `main.ts`:
https://github.com/pyscript/pyscript/blob/42d81db0d012429b41022290337f138c859da152/pyscriptjs/src/main.ts#L27-L56
Previously, a big chunk of the logic was inside `runtime.ts`: the old …

Make the life-cycle more linear and kill some svelte stores

---

pyscriptjs/public/index.html
pyscriptjs/rollup.config.js

The rollup configuration was not set to allow copy during production build.
- copy index.html to build directory ever build

Add directly listing for releases (fix error)

---

docs/howtos/passing-objects.md

Fixes typo in HTML example: `do-mmath` -> `do-math`

Fix typo in passing-objects.md

---

pyscriptjs/tests/integration/test_03_style.py

Hi,
This PR removes an unused import to resolve the following pre-commit error:
```console
$ pre-commit run flake8 --all-files
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
pyscriptjs/tests/integration/test_03_style.py:1:1: F401 're' imported but unused
import re
^
1     F401 're' imported but unused
```

Remove an unused import

---

docs/tutorials/getting-started.md

Add note on [[runtimes]] TOML table in docs
"Note: [[runtimes]] is a TOML table, make sure this is last in a py-config as the properties defined after it goes into the runtimes object."
Fixes #859

Add note on [[runtimes]] TOML table in docs

---

pyscriptjs/tests/integration/test_zz_examples.py

there is no point having a red build while we wait for the fix.
See #864

skip test_repl as it's flaky

---

pyscriptjs/jest.config.js

Hi,
This PR migrates the Jest config to resolve the following warning:
```console
$ npm run test
> pyscript@0.0.1 test
> cross-env NODE_OPTIONS=--experimental-vm-modules jest --coverage
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
...
```
Ref: https://kulshekhar.github.io/ts-jest/docs/getting-started/options

Migrate the Jest config

---

pyscriptjs/tests/integration/conftest.py

The docstring says everything:
```
At the moment of writing this conftest defines two new options, --dev and
--no-fake-server, but because of how pytest works, they are available only
if this is the "root conftest" for the test session.
This means that if you are in the pyscriptjs directory:
$ py.test                       # does NOT work
$ py.test tests/integration/    # works
This happens because there is also test py-unit directory, so in the first
case the "root conftest" would be tests/conftest.py (which doesn't exist)
instead of this.
There are various workarounds, but for now we can just detect it and
inform the user.
Related StackOverflow answer: https://stackoverflow.com/a/51733980
```
The error message looks like this:

try to display a reasonable message if you run a bare 'pytest' command

---

docs/tutorials/getting-started.md
pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/src/pyconfig.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/tests/integration/test_py_config.py
pyscriptjs/tests/unit/runtime.test.ts

Upgrade to Pyodide 0.21.3 as the default. The [changelog from 0.21.2 -> 0.21.3](https://pyodide.org/en/stable/project/changelog.html#version-0-21-3) is mostly bug fixes (including a couple regressions in 0.21.2) - the only breaking changes involves how the `soupsieve` package loads.
The rest of the fixes - including [loading packages in a more sensible order](https://github.com/pyodide/pyodide/pull/3020) and [being able to access the Pyodide version without having to use loadPyodide()](https://github.com/pyodide/pyodide/pull/3074) seem minor but potentially useful.

Upgrade to Pyodide 0.21.3

---

pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/components/pytitle.ts
pyscriptjs/src/components/pywidget.ts
pyscriptjs/src/logger.ts
pyscriptjs/src/main.ts
pyscriptjs/src/pyconfig.ts
pyscriptjs/src/pyexec.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/src/runtime.ts
pyscriptjs/src/utils.ts
pyscriptjs/tests/unit/utils.test.ts

I started adding some types in an effort to fix #834 but Jeff discovered the issue and fixed it :smile: 
This PR adds a bit of typing across the board - I'm still learning how to use the more advanced features of typescript, so there are some changes that I am unsure of :thinking: 
Also I'm not entirely sure if we should replace some/all of these `any` for `unknown`

Add more type definitions

---

pyscriptjs/src/utils.ts

Hi,
This PR changes `window` and `global` to `globalThis` to simplify an implementation.
Ref: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/globalThis

Use `globalThis`

---

CONTRIBUTING.md
docs/development/deprecation-cycle.md
docs/development/developing.md
docs/development/index.md
docs/development/setting-up-environment.md
docs/reference/API/display.md

This is the first pass at adding a `development` section for our docs, I've moved `setting up your env` and `developing` from contributing.md into two specific pages. The section in contributing was replaced by a shorter one that also points to these pages in the docs.
The development section is not included in the navbar, should it? I thought that this might be too specific and users might not care if they aren't creating PRs :thinking: 
Please let me know if you would like me to change anything :smile: 
Closes: #907
Fixes: #448

Add development section to our docs

---

docs/development/developing.md
pyscriptjs/tests/integration/conftest.py
pyscriptjs/tests/integration/support.py
pyscriptjs/tests/integration/test_00_support.py

This allows to run tests offline (if the cache is already populated), and to make them much faster if you are on a slow connection.
Running a single tests went from ~8s to ~5s on my machine.
Moreover, write some docs about the various pytest options that we have and use.

Make HTTP cache persisten across sessions

---

pyscriptjs/src/exceptions.ts
pyscriptjs/src/main.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/tests/integration/test_py_config.py

This PR adds a check to the status code of `fetch` and if we get any non 200 then we throw an error.
This was a bit of a quick hack, but now I am wondering if perhaps we should handle only any 300+ errors? 🤔  If we are getting something is likely that we will always get a 200 right? 
Fixes: #934

Raise error if we get a non 200 status from fetch

---

pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_01_basic.py

I noticed the comment about not handling errors when we fetch the src from py-script, this PR handles any non-200 status code, creates a banner and raises a FetchError

Handle non-200 code when fetch py-script src

---

pyscriptjs/src/exceptions.ts
pyscriptjs/src/main.ts
pyscriptjs/src/utils.ts
pyscriptjs/tests/unit/exceptions.test.ts

This is a small PR that changes how the `_createAlertBanner` works, before this, we were adding the message to `innerHTML`, now the message will be attached to `textContent` by default, but allows you to specify `html` if you want to send HTML to the banner.
Close: #924

Add flag to send HTML or plain Text to banner

---

pyscriptjs/src/components/pybox.ts
pyscriptjs/src/components/pybutton.ts
pyscriptjs/src/components/pyinputbox.ts
pyscriptjs/src/components/pytitle.ts

When working on #924  I forgot to change the deprecated message, since we are sending text by default, the escaped characters were added as is and that broke CI.
This PR fixes the deprecation message
cc @madhur-tandon

Fix deprecated message and tests

---

.github/workflows/prepare-release.yml

I used `act` to check if this would run successfully (using dry-run) and got a green checkmark, hopefully it will work 😬 
With this PR the `prepare-release` action should zip the `build` folder and include it in the release. There's also an action to zip files/folders, but assuming that `zip` is included in the ubuntu instance, the command should work.
Fixes: #851

Zip the build folder and add it to release

---

docs/guides/asyncio.md
docs/guides/index.md
docs/index.md
examples/bokeh_interactive.html
examples/numpy_canvas_fractals.html
examples/webgl/raycaster/index.html
pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/pyexec.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/src/python/pyscript.py
pyscriptjs/src/runtime.ts
pyscriptjs/tests/integration/test_03_async.py
pyscriptjs/tests/integration/test_importmap.py
pyscriptjs/tests/integration/test_py_config.py
pyscriptjs/tests/integration/test_py_repl.py
pyscriptjs/tests/py-unit/test_pyscript.py

This removes the ability to write "implicitly scheduled coroutine" code in \<py-script\> tags, and requires users to use known asyncio methods to run coroutines, like `ensure_future()` or `create_task()`. It reverts from the use of Pyodide's `runPythonAsync()` to `runPython()`.
Fixes #879. See discussion in that issue.
This PR has a completed todo list and is ready for review.
----
To be clear, users still absolutely still have the ability to run code asynchronously. All of these still work:
```html
<py-script>
import asyncio
async def main():
display("I see you shiver with anticip", target="rocky-horror-quote")
asyncio.sleep(5)
display("...pation", target="rocky-horror-quote")
asyncio.ensure_future(main())
</py-script>
```
```html
<py-script>
from js import console
import asyncio
from …
```

Remove 'Implicit Async', Don't Await `runtime.run()`

---

examples/altair.html
examples/folium.html
examples/matplotlib.html

Some examples had a div with an id and we were rendering things onto this div, in some cases (like Altair) this div had a style of `width: 100%; height:100%` which made the example render way below the viewport.
This small PR adds `target=` to the display function so they get displayed in the top level div (we could also remove them, but maybe it's a good example of how to use display? 🤔 )

Add div id to target in the  display so examples get displayed in the right tag

---

docs/reference/API/__version__.md
docs/reference/API/versIon_info.md
pyscriptjs/__mocks__/_pyscript.js
pyscriptjs/__mocks__/fileMock.js
pyscriptjs/jest.config.js
pyscriptjs/src/pyodide.ts
pyscriptjs/src/python/pyscript.py
pyscriptjs/tests/integration/test_01_basic.py
pyscriptjs/tests/py-unit/test_pyscript.py

After Ted's PR earlier this week (#952), here's a small-ish PR to access that version in Python as well. It adds `PyScript.__version__` and `PyScript.version_info`:
```python
>>> PyScript.version_info
version_info(year=2023, month=2, patch=1, releaselevel='dev')
>>> PyScript.__version__
'2023.02.1.dev'
```
This fixes #546 , and supercedes #833.

Import PyScript Version into Python Runtime

---

docs/reference/modules/pyscript.md
pyscriptjs/src/main.ts
pyscriptjs/tests/integration/test_01_basic.py

Exports the version number as an attribute of the JS module.
```html
<script defer 
src="https://pyscript.net/latest/pyscript.js"
onload="console.log(`${pyscript.version}`)" 
>
</script>
```
```js
//example result
Object { year: 2022, month: 11, patch: 1, releaselevel: "dev" }
```
Though the version number is stored in `runtime.ts`, it's really a version number for PyScript, not the runtime, so it's exported as an attribute of the `pyscript` module itself instead of the `runtime`.
Updated `/docs/modules/pyscript` with this info.

Export Version from JS Module

---

pyscriptjs/src/styles/pyscript_base.css

As I mentioned in issue #966, this PR fixes that the cursor style is set to 'text' for all input types. This is necessary because some types (like 'range') use the default cursor style. 
Fixes: #966

Remove hardcoded cursor for <input>

---

docs/tutorials/getting-started.md

This PR addresses #973 by editing the _Writing into labeled elements_ example in the [getting-started](https://docs.pyscript.net/latest/tutorials/getting-started.html) tutorial. It replaces references to, and instances of, the deprecated `pyscript.write(<id>, message)` method with `Element(<id>).write(message)`

remove deprecated ref in getting started doc

---

pyscriptjs/src/main.ts

Hi,
This PR changes to use a more precise type instead of the `any` type.
Note: It uses `ReturnType<typeof make_PyScript>` as an alternative to `typeof PyScript` because the `PyScript` type is not exported.

Use a more precise type

---

examples/panel_kmeans.html
examples/repl.html
examples/repl2.html
pyscriptjs/src/plugins/splashscreen.ts
pyscriptjs/tests/integration/test_zz_examples.py

Tests in main have been failing since #968 was merged, this PR fixes the failing tests. Looking into it, it seems that the failures are caused by:
- importing pyscriptjs twice
- The 'view code' button was blocking the run button so playwright couldn't click it
- The logo in the navbar was being picked up in the matplotlib
Not sure what's happening yet, but running `pytest` manually sees to produce different failures than when we run `make test-integration-parallel`.  
These failures weren't also caught by our CI because it's being run only when we have changes to pyscriptjs  and the above PR only changed things in the example folder

Fix failing integration tests

---

docs/error.md
docs/reference/elements/py-config.md
docs/tutorials/deployment.md
docs/tutorials/getting-started.md
docs/tutorials/index.md
docs/tutorials/py-config-fetch.md
docs/tutorials/py-config-runtime.md
docs/tutorials/setup.md
docs/tutorials/writing-to-page.md

This PR does a few things:
- Adds a tutorial for [[fetch]]
- Adds a tutorial for [[runtimes]]
- Add a 404 error template (its in markdown so it has the docs theme and users can use the search bar)
- Small tweaks to references
- Removes the "Coming soon" pages (deployment, setup)

Add three new tutorials and small tweaks to docs

---

pyscriptjs/tests/integration/test_02_output.py

Fixed the tests that were xfail or failing + added a new test to make @antocuni happy.
Intends to close #878

Fix test and add new ones to close 878

---

docs/reference/exceptions.md
docs/reference/index.md
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/components/pywidget.ts
pyscriptjs/src/exceptions.ts
pyscriptjs/src/fetch.ts
pyscriptjs/src/main.ts
pyscriptjs/src/plugins/fetch.ts
pyscriptjs/src/plugins/pyterminal.ts
pyscriptjs/src/pyconfig.ts
pyscriptjs/src/pyexec.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/src/utils.ts
pyscriptjs/tests/integration/test_01_basic.py
pyscriptjs/tests/integration/test_py_config.py
pyscriptjs/tests/unit/exceptions.test.ts
pyscriptjs/tests/unit/fetch.test.ts
pyscriptjs/tests/unit/main.test.ts
pyscriptjs/tests/unit/pyconfig.test.ts
pyscriptjs/tests/unit/pyodide.test.ts
pyscriptjs/tests/unit/utils.test.ts

This PR adds error codes and documentation for our custom errors.  There is still a few items left to do on the PR:
On the 'handle fetch errors better' front, I am planning to create a custom function that will call fetch under the hood, but handles the status codes and includes the respective error code so we can replace the `errorCode` type from string to ErrorCode similar to `UserError`
Closes: #956

Add error codes to our custom errors

---

docs/reference/elements/py-config.md
docs/tutorials/getting-started.md
examples/simple_clock.html
pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_02_output.py

This PR deprecates the `output` attribute in the `py-script` tag and updates the docs that use it.
Closes: #973

Deprecate pyscript output attribute

---

pyscriptjs/src/fetch.ts

When I wrote the `robustFetch` I was wondering if we should fail on any code that's not a 200. The fetch API will set `response.ok` for any 200-299 status code. 
This PR updates the logic to use this instead of a check on `response.status`

Use response.ok instead of just status 200

---

docs/reference/exceptions.md
pyscriptjs/src/exceptions.ts
pyscriptjs/src/main.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/tests/integration/test_01_basic.py

Currently when we try to install a package that does not exist or there are no pure wheels for, things fail *silently* (we do have console logs), and the splash screen also doesn't close.
This PR handles exceptions on `await micropip.install` and throws a new error InstallError (should we reuse the fetch error instead?). It also addresses a comment left by @antocuni  that, ideally, we should only load micropip if we have packages to install.
After this PR, the load screen will close and the alert banner will be shown with a helpful message. Unfortunately, we can't simply use the exception message because it contains a big Python traceback.
Fixes: #911

Improve UX when we can't install a package

---

docs/reference/elements/py-config.md

This changes a few things that @FabioRosado's PR does in #982, although they are very minor.
Fetch section updated in https://github.com/pyscript/pyscript/pull/1019
This PR doesn't touch on `<py-config>` being inside `<body>` tags owing to discussions by @JeffersGlass and @antocuni 
Closes https://github.com/pyscript/pyscript/issues/1006

split py-config into sections

---

examples/panel.html

This bumps the version of `panel` from 13.1 to 14.1, to avoid showing a deprecation warning for the use of `pyodide.to_js` which was still present in the earlier version of panel.
Also bumps the version of `bokeh` from 2.4.2 to 2.4.3 to avoid a warning in the console about a mismatch between bokeh and Python versions, caused by the panel version increase.

Bump bokeh, panel versions

---

pyscriptjs/environment.yml
pyscriptjs/src/plugins/python/py_markdown.py
pyscriptjs/tests/integration/test_zz_examples.py
pyscriptjs/tests/py-unit/conftest.py
pyscriptjs/tests/py-unit/test_python_plugins.py

Unescape the tag content before actually running `markdown` and actually explicitly import console since we now are importing pyscript as a module

Fix py-markdown plugin

---

pyscriptjs/tests/integration/test_01_basic.py

A small PR - the change to `test_version_info` to remove an extraneous '.' from the regex checking the 'releaselevel'.

Adjust `test_version_info` - no dot in releaselevel

---

docs/tutorials/getting-started.md

Example script gave warning: "Direct usage of document is deprecated. Please use js.document instead."
Added "js."

Fixed "Direct usage of document is deprecated." warning

---

pyscriptjs/rollup.config.js

`pyscript.min.js` does not currently export `pyscript` as a JavaScript module, meaning that all the functionality that's intended to be exposed via [the pyscript js module](https://docs.pyscript.net/latest/reference/modules/pyscript.html) does not work when using the minified version.
This PR rectifies that by adding `name: "pyscript"` to the the minified configuration in the rollup config. I also re-arranged the keys in the normal and minified versions so they're in the same order.
First spotted by user "tuxprint" on the PyScript Discord.

Add name: "pyscript" to rollup config for minified verison

---

pyscriptjs/src/python/pyscript.py
pyscriptjs/tests/integration/test_plugins.py

Python plugins were being registered with the App's plugin manager twice: once in `fetchPythonPlugins`:
https://github.com/pyscript/pyscript/blob/c0f36aa047fb967c2dfe9d98bda836fb01e29ba1/pyscriptjs/src/main.ts#L294-L297
And once in the `init` method of the Python Plugin class itself:
https://github.com/pyscript/pyscript/blob/c0f36aa047fb967c2dfe9d98bda836fb01e29ba1/pyscriptjs/src/python/pyscript.py#L498-L500
This PR removes the second registration, and improves `test_execution_hooks` to check that the specified hooks are called _exactly_ once, instead of at least once.
Fixes #1049

Don't add Python Plugins to Manager Twice

---

pyscriptjs/src/logger.ts
pyscriptjs/src/pyconfig.ts

- logger.ts
- Comment readability improvement
-  String interpolation instead of string concatenation
- pyconfig.ts
- Use shorthand syntax for object property 
- Refactor parseConfig
- Extract a function to generate errors
- Return config directly instead of setting a variable and returning it at the end of the function

Minor refactoring in logger and pyconfig

---

CHANGELOG.md
CONTRIBUTING.md
docs/changelog.md
docs/development/developing.md
docs/index.md
docs/tutorials/index.md

We are still talking about the changelog in #1060, but we may be inclined to start by writing it manually. 
This PR adds the `changelog.md` file under the root of our `docs/` and also adds the link to the header.
We could also move the changelog outside the docs and link it to github if you think that's better 😄

Add changelog to docs

---

pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_splashscreen.py

If a user adds a `pys-onClick` or `pys-onKeyDown` we are adding the event listener using Element and pyodide. Although any exception in the code, prevents the splashscreen to close.
This PR simply adds a try/catch  so the splashscreen doesn't just hang.
I think these attributes will (or should) be removed before the next release, but maybe it's okay to add the try/catch for now
Fixes: #1068

pys-onClick shouldn't prevent splashscreen from closing on errors

---

pyscriptjs/src/fetch.ts
pyscriptjs/src/main.ts
pyscriptjs/src/pyconfig.ts
pyscriptjs/src/runtime.ts
pyscriptjs/src/version.ts
pyscriptjs/tests/unit/pyconfig.test.ts

This PR takes the `version` variable from `runtimes.ts` and adds  it to a new file `version.ts`  as suggested by @mchilvers  in Discord.
There's some sprinkles of changes due to eslint.

Add version file to keep pyscript version

---

pyscriptjs/src/components/pyrepl.ts
pyscriptjs/tests/integration/test_py_repl.py

A minor change to the CodeMirror configuration used for py-repl to prevent `shift`+`enter` from inserting a newline. Added a test for this.
Fixes #984

In a Py-Repl, Shift Enter Shouldn't Insert Newline

---

pyscriptjs/tests/integration/support.py
pyscriptjs/tests/integration/test_py_repl.py
pyscriptjs/tests/integration/test_zz_examples.py

Fixes an issue where `test_execute_on_shift_enter` test was "flaky", passing intermitantly.
The root cause of the issue was one of timing. There was no explicit wait for whether the code inside the py-repl had been executed by the time we reached the relevant `assert` statements. So, sometimes, by luck, it would have executed and the console log would contain the relevant text ("hello world"). Sometimes, it wouldn't have finished executing, and the console log would be wrong. 
The solution involved re-using the `wait_for_render` function (now moved into `support.py`) to ensure that "hello world" is rendered on the page before checking for it in the captured log lines.
As a data point:
- Prior to this change, 19 out of 40 iterations of this test succeeded.
- After the change,     40 out of …

Fix Flaky `test_execute_on_shift_enter`

---

setup.cfg

It seems that the latest version of flake8 is causing pre-commit to fail, this is happening because it's suggested that we use `!r` instead of using `"{test}"`. This causes lines such as these to fail;
```
pyscriptjs/src/python/pyscript.py:52:12: B028 'data' is manually surrounded by quotes, consider using the `!r` conversion flag.
return f'<img src="{data}" {attrs}></img>'
```
I think for our use-case, we should explicitly add the quotes since it makes it clearer and prevent us from missing the `!r` in fstrings.

Add f-string quotes rule to flake8 ignore

---

docs/changelog.md
pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_01_basic.py

This is a follow up from https://github.com/pyscript/pyscript/pull/1093 which aimed to improve user/dev experience by showing an alert banner in the page if the user forgot to add an id to the element which contains a `py-` attribute.
With this PR we will simply call `ensureUniqueID` to attach a unique id to te element, I think this way is better than the previous PR because:
- Takes the overhead from the user, it just works
- Keep developers from having to go back and add a bunch of id's if they used a lot of py- attributes but none has ids
- it just works?
Usually magic is a bad idea, but in this case it might be okay :thinking:

Add an id if the user forgot when using py-attribute

---

pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/plugin.ts
pyscriptjs/src/plugins/stdiodirector.ts
pyscriptjs/tests/integration/test_plugins.py

In #1063, we/I introduced a couple of new lifecycle hooks that took several positional arguments, like so:
```ts
//Before: bad
beforePyScriptExec(interpreter: Interpreter, src: string, pyscriptTag: HTMLElement)
afterPyScriptExec(interpreter: Interpreter, src: string, pyscriptTag: HTMLElement, result)
```
This is unfortunately error-prone, as it's easy for users to get the argument error wrong. There were even a couple of tests in the PR where _I_ got the order wrong, which happened to pass by chance! 😶
---
This PR changes the interface for both of those hooks, and sets a precedent for arguments for future hooks. Instead of lots of positional arguments, these hooks now accept an [options object](https://www.codereadability.com/what-are-javascript-options-objects/) with the desired …

Change Plugin Hooks to Use options object/kwargs

---

pyscriptjs/src/plugin.ts
pyscriptjs/src/plugins/stdiodirector.ts

Improves the typing of the `pyScriptTag` argument to the `beforePyScriptExec` and `afterPyScriptExec` hooks that were added in #1063 .
Previously, it was just an `HTMLElement`. Now it is properly typed, using 'InstanceOf' and 'ReturnType' to type that argument as an instance of the class returned from `make_PyScript()`.

Improve typing on PyScriptTag Object

---

pyscriptjs/src/plugins/python/py_markdown.py

Fixes https://github.com/pyscript/pyscript/issues/1107
Source: https://stackoverflow.com/questions/59052079/pyinstaller-and-python-markdown-importerror-no-module-named-extra

fix py-markdown plugin test

---

docs/changelog.md
docs/reference/plugins/py-splashscreen.md
pyscriptjs/src/plugins/splashscreen.ts
pyscriptjs/tests/integration/test_01_basic.py
pyscriptjs/tests/integration/test_splashscreen.py

This PR adds a `disabled = false` option to the splashscreen which allows users to disable it if they so wish to do so. It also adds docs for the `py-splashscreen` and how to add custom messages to the splashscreen 😄 
Fixes: #900
Closes:  #1004

Add config option to splashscreen so users can disable it plus docs

---

docs/tutorials/getting-started.md

Small fix for the get started tutorial so we don't show the import warning when trying to use js directly

Fix import warning for js.document in get started tutorial

---

docs/development/developing.md
examples/bokeh.html
examples/bokeh_interactive.html
examples/panel.html
examples/panel_deckgl.html
examples/panel_kmeans.html
examples/panel_stream.html
pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/src/pyconfig.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/tests/integration/test_py_config.py
pyscriptjs/tests/integration/test_zz_examples.py

Closes https://github.com/pyscript/pyscript/issues/1092
1. `Python Initialization Complete` is removed (see https://github.com/pyodide/pyodide/pull/3247) so we add it on our own inside `loadInterpreter()`
2. The following tests are affected:
Tests related to `bokeh`:
- test_bokeh (have been able to fix this)
- test_bokeh_interactive (partial fix owing to inspiration from here: https://github.com/bokeh/bokeh/pull/11960/files#diff-d3c9d0e9a7e1a7ece20833ae12ede8fc63f99bf0f2607627f4e04788c176afd7L101)
Tests related to `panel`:
- test_panel_kmeans
- test_panel
- test_panel_stream
- test_panel_deckgl
We don't have a Panel release which is compatible with bokeh 3.x as told by @philippjfr
Since both `bokeh` and `panel` are pure python packages, thus, examples related to `panel` have `bokeh` as …

Upgrade Pyodide to v0.22.1

---

pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/components/pywidget.ts
pyscriptjs/src/interpreter.ts
pyscriptjs/src/main.ts
pyscriptjs/src/pyexec.ts
pyscriptjs/src/pyodide.ts
pyscriptjs/src/python/pyscript.py
pyscriptjs/src/utils.ts
pyscriptjs/tests/integration/test_01_basic.py
pyscriptjs/tests/integration/test_async.py
pyscriptjs/tests/integration/test_splashscreen.py
pyscriptjs/tests/integration/test_stdio_handling.py
pyscriptjs/tests/unit/pyodide.test.ts

CC: @JeffersGlass @antocuni @hoodmane 
TODO comments still required at two places.
Thing to consider: In `pyrepl.ts` -- should the call to `pyExec` be inside a mutex lock? Just the way it was done for the `pyExec` call in `pyscript.ts`

wrap runPython in async

---

pyscriptjs/tests/integration/test_async.py

This fixes an issue with the `test_asyncio_gather` test. The test should be comparing the test string against the list of results `[3, 2, 1]`, but it was being compared with the string representation of the PyProxy of the list of results `[3,2,1]`, with different spacing. By specifying that we want to compare directly with the string representation, instead of the `to-js()` version (which did essentially nothing), this issue is resolved.

Fix `test_asyncio_gather`

---

pyscriptjs/src/python/pyscript.py

Try new import path first then fall back to old one

Fix deprecation warning for `pyodide.create_proxy`

---

pyscriptjs/src/main.ts

Uses `ReturnType` to add typing to the App's tagExecutionLock. Eliminates 3 linting errors.

Add typing for `tagExecutionLock`

---

docs/Makefile
docs/README.md
docs/conf.py
docs/reference/API/display.md

This PR adds sphinx intershinpx so we can create cross references to python docs both the glossary and builtin functions.
For example the display was mentioning `ref()` but there was no cross-reference to the python docs. This PR adds it

Add intersphinx and some docs

---

pyscriptjs/tests/integration/test_async.py

The integration test `test_multiple_async` had accounted for the deprecation warnings caused by `from pyodide import ffi`; now that those are fixed by #1223, the test has been adjusted to correctly pick out the lines that have the test's output.

Fix Failing `test_multiple_async` Test

---

pyscriptjs/src/main.ts
pyscriptjs/src/remote_interpreter.ts

Suggested by @hoodmane, the undocumented API for `FS.mkdirTree` can be used to avoid creating nested paths by iteration.
The PR is marked WIP since some tests fail.
For example, one of the tests fail due to:
`this.interface.FS.writeFile(path, data, {canOwn: true})` resulting in an error i.e.
```
{node: undefined, errno: 44, message: 'FS error', stack: '<generic error, no stack>', setErrno: ƒ}
```

use mkdirTree in emscripten FS

---

.github/workflows/build-unstable.yml
.github/workflows/test_report.yml

Test reporter take 3. The problem in the previous case was that `upload-artifacts` is not sensitive to the `working-directory: pyscriptjs` setting, so we have to give the path relative to the **original** working directory. I also added `if-no-files-found: error` so this would fail the ci if it was wrong in the future.

Fix test reporter again

---

.github/release.yml
.github/workflows/build-unstable.yml
.github/workflows/docs-release.yml
.github/workflows/docs-review.yml
.github/workflows/docs-unstable.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
.github/workflows/sync-examples.yml
.github/workflows/test_report.yml
.pre-commit-config.yaml
.prettierignore
.readthedocs.yml
examples/handtrack/say_hello.html
examples/mario/play_mario.html
pyscriptjs/environment.yml

This uses my forked version of prettier. Prettier has no API to ask it to leave `py-script` and `py-config` alone, but it does have an internal method.
See my precommit hook here: https://github.com/hoodmane/pyscript-prettier-precommit
@FabioRosado It would be better to rebase-merge / merge-merge this and not to squash merge, since commit 2 is 378 lines of automated changes (another option would be to split into two prs and temporarily disable pre-commit.ci between them, but that's more annoying)

Add prettier to pre-commit

---

pyscriptjs/tests/py-unit/conftest.py

The path logic here assumes that the tests are being run from inside the 
pyscriptjs directory. It is better to compute releative to `Path(__file__)` 
so that it does not depend on the working directory

Fix paths in py-unit/conftest.py

---

.github/workflows/build-unstable.yml
.pre-commit-config.yaml

precommit.ci seems to have different results than when I run eslint locally. 
At least at first glance, github seems to behave the same as local. So this
turns off eslint in pre-commit.ci and turns it on in gha.

Run eslint in github actions, skip it in precommit.ci

---

.github/workflows/sync-examples.yml

This PR adds `workflow_dispatch` to the sync examples action so we can trigger it manually from within github itself. This should allow us to publish examples and fix the issue with py_tutor without doing a full release.

Update sync-examples CI to be run manually as well

---

examples/altair.html
examples/antigravity.html
examples/bokeh.html
examples/bokeh_interactive.html
examples/d3.html
examples/folium.html
examples/hello_world.html
examples/markdown-plugin.html
examples/matplotlib.html
examples/message_passing.html
examples/numpy_canvas_fractals.html
examples/pandas.html
examples/panel.html
examples/panel_deckgl.html
examples/panel_kmeans.html
examples/panel_stream.html
examples/repl.html
examples/repl2.html
examples/simple_clock.html
examples/todo-pylist.html
examples/todo.html

At the moment of writing, pyscript.net/examples/* are broken because they try to load the plugin `../build/plugins/python/py_tutor.py`.
This is wrong, they should reference `pyscript.net/latest/plugins/python/py_tutor.py` instead.
This is what happened:
1. the git pyscript/examples directory is the one which goes straight to pyscript.net: it is supposed to contain absolute links to e.g. pyscript.net/latest/pyscript.js etc.
2. when you do make examples, the makefile replaces links to pyscript.net to ../build/ so that the examples also work locally
3. in PR #1040, @fpliger changed the source code in pyscript/examples to point to a plugin in ../build/: but this is wrong! It should point to pyscript.net (and then the makefile fixes the link automatically when we do `make examples`).

Fix examples broken because of a wrong link

---

docs/changelog.md
docs/reference/plugins/py-terminal.md
pyscriptjs/src/plugins/pyterminal.ts
pyscriptjs/src/styles/pyscript_base.css
pyscriptjs/tests/integration/test_py_terminal.py

Make the default auto terminal docked at the bottom of the document.
As discussed with Antonio, this MR does the following:
* it accepts an optional `docked` configuration option, which is `"docked"` by default
* the attribute behaves just like the `auto` one
* the *py-terminal* is fixed at the bottom of the page, keeping the underlying page scrollable
Accidentally this PR also fixes an issue with `terminal = true` not being treated like `terminal = "auto"`.
There is some TODO/TO-DISCUSS here around extra possible features or behavior so this is some sort of PoC.

Docked auto py-terminal

---

docs/changelog.md
pyscriptjs/tests/integration/test_py_repl.py

In the end the problem was simply a osx vs other os problem.
The `autogen` fix comes from me not paying attention in the past while changing the autogen functionality. Sorry for that!
fixes #1280

Fix tests running on osx + remove auto-gen where doesnt make sense

---

.pre-commit-config.yaml

Weekly autoupdate creates a lot of noise. Quarterly is more reasonable.

Set pre-commit autoupdate to monthly

---

pyscriptjs/src/components/pyrepl.ts
pyscriptjs/tests/integration/test_py_repl.py
pyscriptjs/tests/integration/test_zz_examples.py

This PR slightly simplifies some dance around *py-repl* component without tackling other concerns we still need to discuss. The code has been cleaned up a bit, simplified, and it should be less error prone.
* removed unnecessary `getAttribute`
* removed unnecessary *shadow* and ShadowDOM in general, as it was never used
* dropped redundant constructor
* reused `addReplAttribute` for both attributes
* removed unnecessary usage of the label element + fixed redundant always-same buttons IDs

Slightly imporved pyrepl

---

pyscriptjs/src/plugin.ts

Makes the new methods `beforePyReplExec` and `afterPyReplExec` from #1106 optional for plugin classes, just like I did for all the other methods in #1134.  An oversight of mine, working on both of those PRs at once.

Make repl hooks optional

---

.github/ISSUE_TEMPLATE/config.yml

They were disabled by PR #1157 but without any discussion or consensus, so I guess it was a mistake. Personally I found them very useful and AFAIK we never had a problem of people abusing them, so I don't see why they should be disabled

re-enable blank issues

---

pyscriptjs/esbuild.js
pyscriptjs/src/interpreter_client.ts
pyscriptjs/src/main.ts
pyscriptjs/src/remote_interpreter.ts

Followup to #1232. Closes #1226.
Use node to make a manifest of the src/python dir and then use an esbuild plugin to resolve an import called `pyscript_python_package.esbuild_injected.json` to an object indicating the directories and files in the package folder. This object is then used to govern runtime installation of the package.

Allow pyscript package to contain multiple files

---

docs/changelog.md
docs/development/deprecation-cycle.md
examples/handtrack/say_hello.html
examples/mario/play_mario.html
pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_01_basic.py

As described in #1220, the `py-mount` attribute isn't a feature we really advertise, nor make use of anywhere else in the codebase. It was meant to mount HTML elements directly as pyscript `Element`s, but that's nor really a part of the API we're suggesting at this point.
Also added a section of the deprecation docs for **tracking what's currently being deprecated** so that we actually remember to remove deprecated things in a future release. 😅
Fixes #1220

Deprecate `py-mount` Attribute

---

.github/workflows/docs-review.yml

The `docs-review` action breaks on every PR that includes changes to the docs. The action tries to upload a copy of the built docs to AWS, presumably for easier review. However, as I understand it, actions triggered by PR's not from the repo's owner are run with the credentials of the *contributor* for security reasons. So the AWS secrets are not accessible, and the action fails.
This just removes the attempted AWS upload step from the PR tests. Since we've never had it working in the first place, I don't think we'll miss it. The docs still get built on merge/release.
Fixes #1294

Un-break Docs CI

---

pyscriptjs/tests/integration/support.py
pyscriptjs/tests/integration/test_00_support.py
pyscriptjs/tests/integration/test_zz_examples.py

Improve `self.wait_for_console()`: previously, if the message appeared on the console immediately before the call to `self.wait_for_console()`, the call would hang forever until the timeout.
Now, it returns immediately.

Improve self.wait_for_console()

---

.pre-commit-config.yaml
pyscriptjs/package-lock.json
pyscriptjs/package.json

This PR updates TypeScript and related packages to the latest versions.
- Update TypeScript 4.8.4 to 5.0.4
- Update @typescript-eslint/eslint-plugin 5.39.0 to 5.58.0
- Update @typescript-eslint/parse 5.39.0 to 5.58.0

Update to the latest TypeScript

---

docs/tutorials/index.md

"How to write content to the page" appeared twice in the index.

doc: remove duplicated link

---

pyscriptjs/src/plugin.ts
pyscriptjs/src/plugins/pyterminal.ts
pyscriptjs/tests/unit/plugin.test.ts

This improves the previous `validate()` function in pyterminal.ts to be more flexible in how it handles potential values and default values. Previously, configuration options could only be booleans or strings, and the default *had* to be a string. 
Now, the options can be any of the non-array types (string, boolean, number or Object) that could be present in the TOML/JSON from py-config, any of them can be the default, ~~*and* the type system will catch whether the listed default value is indeed part of the array.~~
I've moved `validate()` - now renamed to `validateConfigParameter()` - from pyterminal.ts to plugin.ts, but only used it to improve pyterminal.ts for now to make it easier to see what's changed. We can use it to validate parameters for the other plugins in follow-up PRs. I've …

Improve `validate()` function for plugin options

---

pyscriptjs/package-lock.json
pyscriptjs/package.json

It seems that esbuild doesn't support to import helpers for now.
- Remove tslib

Remove an unused dependency

---

pyscriptjs/src/components/pywidget.ts
pyscriptjs/src/plugin.ts

This MR would like to cleanup a tiny redundant property we type and set at the Custom Element level, likely ignoring the fact a `shadowRoot` field is attached to the element already when `attachShadow({mode: 'open'})` is used.
Remove the unused and unnecessary `shadow` property/field from our Custom Elements.

Remove redundant `.shadow` property as that is defined at the CE level

---

docs/reference/elements/py-config.md

fixed typo.
unspecifed -> unspecified

Fix typo in py-config.md

---

docs/tutorials/getting-started.md

In the PyScript tutorial yesterday, one of our users was having issues following our Getting Started docs, since her setup didn't allow files opened from disk to access remote resources. The info on using a local dev server (`python -m http.server 8080`) is in our error messages, but isn't actually in our documentation. This fixes that omission.

Add 'Using a Local Dev Server' to Getting Started Docs

---

.github/PULL_REQUEST_TEMPLATE.md

Adds some clarifications to the Pull Request template, specifically around what does and does not require a changelog entry, since that's been something that's needed clarification in several recent PR's.

Clarify PR Template - Doc Changes Don't Need Changelogs

---

docs/environment.yml

PR #1255 added prettier to the pre-commit hooks for PyScript, which is awesome. Prettier requires NodeJS 14+, so to ensure that we have the appropriate version available when commit from within the `docs/_env` conda environment, this PR makes a single-line change to `docs/environment.yml`.

Add `nodejs=16` to docs conda environment

---

pyscriptjs/tests/integration/test_zz_examples.py

There are 4 randomly failing tests that often give me a timeout issue (on my machine).
I'd like to propose a timeout for these too.
Use the higher timeout other tests use for:
* test_folium
* test_numpy_canvas_fractals
* test_altair
* test_matplotlib

Increase commonly failing tests timeout

---

docs/changelog.md
docs/development/setting-up-environment.md

Following the development setup docs, running make setup will fail if you don't have anaconda installed. This should be documented.
Documents anaconda requirement higher up in the dev setup guide.

Adds missing dependency description (anaconda) to docs

---

docs/changelog.md
docs/reference/elements/py-script.md
pyscriptjs/.eslintrc.js
pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_01_basic.py

This MR would like to gracefully explore the possibility to use a `<script>` tag to define Python content, as opposite of using a generic Custom Element that gets inevitably parsed by browsers.
See https://github.com/pyscript/pyscript/discussions/1326
No relevant changes to current logic, just an added feature.
* a unique *MutationObserver* is used to intercept new scripts with `type="py"`, `type="pyscript"` or `type="py-script"` on the page
* the same *MutationObserver* is used to observe *ShadowRoot* elements attached on the fly to catch those scripts within their content too
* beside `ltrim(...)` utility, no extra parsing is ever needed for `<script>` content
* because a `<script>` can't really show or have children, a `<py-script-tag>` companion element (name suggested by current API, …

Fix #1326 - Allow `<script type="py">` tag to work as `<py-script>`

---

pyscriptjs/tests/integration/test_script_type.py

Rather than a *fix* this MR showcases that when special chars are meant and needed, the `<script type="py">` solution works out of the box without any encoding/decoding indirection and without *DOMParser* on its way.
* added a test that proves that with a `<script type="py">` none of the issues presented in #735 exist

Fix #735 - Test <script type="py"> against all special cases

---

pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_script_type.py

After addressing  @JeffersGlass comment on adding more tests for attributes, I've realized that indeed I forgot to propagate the `src` attribute to the companion element.
Everything is now tested though and the `src` works as expected.
* propagate the `src` attribute to the companion element to handle external sources too
* add tests that prove all attributes work exactly like `<py-script>` does

Fix <script src> + test all py-script attributes

---

docs/changelog.md
docs/reference/API/when.md
pyscriptjs/src/python/pyscript/__init__.py
pyscriptjs/src/python/pyscript/_event_handling.py
pyscriptjs/tests/integration/test_01_basic.py
pyscriptjs/tests/integration/test_event_handling.py
pyscriptjs/tests/integration/test_zzz_docs_snippets.py

This adds the `@when` decorator to the PyScript API. It is largely the work of @marimeireles in #1240, with a little reshaping around the newer Pyodide FFI and some test cleanup.
The `when` decorator takes two arguments, `event` and `selector`. It attaches the decorated function as an event handler for the named event to all elements in the DOM that match the selector. If the wrapped function takes a single (non-self) argument, the function will be passed the event object when it is called; otherwise, it is called with no arguments.
- Adds the `@when` decorator in a new module `_event_handling.py`
- Adds tests for the same in new file `test_event_handling.py`
-   [x] I have created documentation for this(if …

Add `@when` decorator

---

pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/main.ts
pyscriptjs/src/plugins/importmap.ts
pyscriptjs/src/plugins/pyterminal.ts
pyscriptjs/src/plugins/splashscreen.ts
pyscriptjs/src/plugins/stdiodirector.ts
pyscriptjs/src/stdio.ts
pyscriptjs/src/utils.ts

This MR would like to address the proposal @ https://github.com/pyscript/pyscript/discussions/1429
* use [basic-devtools](https://github.com/WebReflection/basic-devtools/tree/main#readme) as dependency instead of copy/pasting its parts, so that we also have all the TS guards and good things around its .d.ts definition
* replace any verbose `document.method` with either `$` or `$$` to be explicit if it's a single node or multiple nodes returned
* avoid the usage of live collections such as [getElementsByTagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName#return_value) or [getElementsByClassName](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName) as these require special user's note or warnings in MDN because old, de-facto …

Fix #1429 - Use basic-devtools module

---

docs/changelog.md
pyscriptjs/src/components/pyscript.ts
pyscriptjs/tests/integration/test_runtime_attributes.py

This MR addresses various long-standing issues around `py-*` events added at runtime, injected via `innerHTML`, changed or removed from both already live components and new nodes added during long sessions.
* recycled the same MutationObserver used to observe only scripts so that attributes nodes are also observed in both the `document` and any `shadowRoot` attached in the wild
* simplified the bootstrap of `<script type="py">` nodes without needing to reuse the MO logic
* simplified with previous point the bootstrap of *scripts* also within added nodes
* improved the XPath selector to start from a specific context node and reused the same logic for both initial PyScript bootstrap and all runtime added nodes so that all attributes are addressed
* added logic to remove or add same listener …

Fix #1059 - Observe py-* attributes changes

---

examples/matplotlib.html

As `<script type="py">` alternative landed, and it doesn't suffer any entities related issue, it's likely to be more suitable to show examples with python code that contains entities such as `&lt;` and others.
* use `<script type="py">` instead of `<py-script>` to completely avoid dealing with entities

Fix #1341 - Use <script type="py"> instead to avoid entities

---

.prettierignore
examples/panel.html

This MR simply moves all needed scripts within the tutor and as deferred (parallel download + ordered execution right before *DOMContentLoaded* event).
* make all needed scripts deferred
* move all scripts into the `<py-tutor>` element
* disable prettier as it cannot deal with long URLs attributes

Fix #1425 - Move scripts within the tutor

---

examples/panel.html

~~There's a possible regression with current panel demo, because~~ (see https://github.com/pyscript/pyscript/issues/1446#issuecomment-1534368103) we were deferring pyscript after other scripts but latest change inverted the order. Issue #1446 is likely unrelated but that's where I've noticed we moved the dance within the tutor but the pyscript was left behind.
I don't think current page is causing any issue because of *DOMContentLoaded* event triggered after deferred scripts are in, but it's worth, for clean/consistency sake, to preserve the original order.
* move the pyscript library *after* the rest of the dependencies

Fix #1446 - Move pyscript defer after other dependencies

---

pyscriptjs/src/components/pyrepl.ts
pyscriptjs/tests/integration/test_py_repl.py

This MR goal is to move the codemirror's *EditorView* into a dedicated *div* through its *shadowRoot* to avoid editor style and behavior break in the wild.
* slightly changed the *EditorView* initialization dance
* changed tests to address via *Playwright* "*automagic*" `shadowRoot` crawler the content of the repl
* changed the way external *src* is injected, using the `editor.dom` as root
No user-facing changes.

Fix #1445 - Move the EditorView into ShadowDOM

---

pyscriptjs/src/fetch.ts
pyscriptjs/tests/unit/fetch.test.ts

The key for loading local modules seems to be different now.
https://docs.pyscript.net/latest/reference/elements/py-config.html#local-modules
- Fix an error message when loading local modules failed

Fix an error message when loading local modules failed

---

pyscriptjs/src/main.ts
pyscriptjs/src/plugin.ts
pyscriptjs/src/pyconfig.ts
pyscriptjs/src/pyexec.ts
pyscriptjs/src/utils.ts

I am doing some investigation around the pyscript bootstrap and following "[the boyscout rule](https://levelup.gitconnected.com/the-boy-scouting-rule-a-simple-yet-effective-programming-principle-5d504c7dd993)" I've decided to push some minor cleanup.
* removed `getAttribute` as not-needed indirection of `anyElement.getAttribute(...)` as the check on attribute is weak and the result is always `null` even if the attribute is there but its value is an empty string
* removed any multi class utility because `classList.add(...classes)` and `classList.remove(...classes)` already accept an array of classes
* fixed, or better simplfied, some unnecessary type overhead
* removed a (imho?) not useful at all `globalExport` export which does nothing different from attaching something globally
* sneaked …

Chore - Utils cleanup

---

pyscriptjs/tests/integration/test_03_element.py

This MR simply fixes the test around `element.select(...)` as it wasn't fully testing or working as expected.
* actually verify that the `.select` method returns the right element by tag name
* added a test for `content` use case through a template tag

Fix element.select tests

---

pyscriptjs/src/components/pyscript.ts

There was a bad copy/paste typo in the code related to attributes removal which was passing the test only because we couldn't catch the error (although practically the behavior was correct because the handler was throwing, not because it was doing the right thing).
* use `attributeName` and not the `type` from the record, as the `type` is not the `event.type` but the record type

Fix typo in py-events attributes handling

---

pyscriptjs/package-lock.json
pyscriptjs/package.json
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/python/pyscript/_html.py
pyscriptjs/src/remote_interpreter.ts
pyscriptjs/src/shadow_roots.ts
pyscriptjs/tests/integration/test_shadow_root.py
pyscriptjs/tests/py-unit/_pyscript_js.py

This MR would like to allow the `display` `target=id` operation to reach even elements with a specific ID within any shadow root.
* use `js.pyscript_deep_query_selector(f"#{self._id}")` instead of `js.document.querySelector(f"#{self._id}")` when it's available (currently we have a mock test that fails otherwise but I think it's OK double checking anyway)
* weakly reference shadow roots in an iterable way (added [not-so-weak](https://github.com/WebReflection/not-so-weak#readme) module for this purpose as it's well tested already)
* add a test that ensures, once a `py-script` custom element is bootstrapped/defined, any Shadow Root node can be addressed given the right ID for it
-   [ ] I have created documentation for …

Allow nodes in shadow roots to be addressed via Element

---

pyscriptjs/environment.yml

As we've been [discussing at length on Discord](https://discord.com/channels/972017612454232116/1108339082825830432), the examples tests have been broken in CI/GitHub Actions since Monday. This PR fixes that.
The main issue was that the `pytest` feedstock in the anaconda main channel jumped from 7.1.2 to 7.3.1 on Monday evening, which for some reason broke our test setup. 
```
<item>
<title>pytest 7.3.1 [linux-32, linux-64, linux-aarch64, linux-ppc64le, linux-s390x, osx-64, osx-arm64, win-32, win-64]</title>
<description>The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.</description>
<link>https://docs.pytest.org/en/latest/</link>
<comments>https://github.com/pytest-dev/pytest/</comments> …
```

Fix Examples Tests in CI (Pin `pytest=7.1.2` et al)

---

pyscriptjs/src/exceptions.ts

While digging into the dance around *fetch* files, I stumbled upon this file which looked a bit weird to me so I've decided to somehow apply the "boy-scout rule" and change it.
* removed badly formatted comments
* removed unnecessary comments + added one that made me think more than I should've (errorCode)
* used TypeScript `public` fields to simplify code and avoid redundant info / details
* used inline element creation instead of prop after prop assignments
* used `appendChild` returned value to attach a listener

[chore] Improve current Error extends

---

examples/repl2.html

We forgot to add the `utils.py` file within the list of modules to use in the py-tutor
* added `utils.py;antigravity.py` as `modules` attribute instead of just `antigravity.py` 

Fix #1482 - Add utils.py to the list of modules

---

pyscript.core/esm/index.js
pyscript.core/package.json

This MR ensures the thrown error on possible typos on the page (around runtimes) is actually meaningful.
This MR has been manually tested by changing `mpy-click` to `py-click` within the `test/worker/input.html` manual integration test.
* resolve the runtime only if known
* throw a meaningful error whenever no `<script type="runtime">` has been found in the page

Fix #1514 - Provide a better feedback on HTML typos

---

pyscript.core/esm/runtime/_utils.js
pyscript.core/esm/runtime/micropython.js
pyscript.core/package.json
pyscript.core/test/worker/input.html

There is [a MicroPython specific bug](https://github.com/micropython/micropython/issues/11749) around polyfills and globals and this MR would like to both simplify and avoid polluting globals with all other runtimes that have no issues whatsoever.
* moved the global patch needed only in MicroPython
* simplified the patch and tested it manually via integration
* cleaned up integration as `Promise.withresolvers()` **is** the way to go

[next] Micropython promise

---

pyscript.core/esm/worker/_template.js
pyscript.core/package.json

As @antocuni spotted, once minified and bundled as Blob, the error around being unable to use [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) is way too cryptic.
This MR would like to help understanding security implications when such primitive is meant to be used.
* added an explicit try/catch around the worker Blob minified code

Shared array buffer missing error

---

.github/workflows/test-next.yml

Just wondering if maybe the issue is because we don't really run the tests on next (although core should still run tests when we change this .yml file)

Add step to install next deps and run test

---

pyscriptjs/src/main.ts
pyscriptjs/tests/integration/test_interpreter.py

Restores old behaviour of accessing `pyscript.interpreter` or `pyscript.runtime` as discussed here: https://github.com/pyscript/pyscript/discussions/1489#discussioncomment-6019586 during RC1 testing.

fix access to interpreter globals without awaits

---

docs/changelog.md
docs/reference/elements/py-repl.md
pyscriptjs/tests/integration/test_py_repl.py

The ability to get the text contents of a \<py-repl\> is a long standing feature request (#954, and Stack Overflow [[1]](https://stackoverflow.com/questions/76428228/save-a-repl-session-from-pyscript-py-repl-environment) [[2]](https://stackoverflow.com/questions/74927506/how-to-get-active-repl-block-in-pyscript-and-copy-whatever-code-written-in-it)). 
This PR promotes the existing `getPySrc()` method of a py-repl to be an actual documented feature. It doesn't actually need to add any code, just adds that function to the documentation and provides a couple new tests.
`<py-repl>` gains the `getPySrc()` method as public-facing API.

Make getPySrc() a Documented Feature

---

pyscriptjs/src/components/pyrepl.ts
pyscriptjs/src/components/pyscript.ts
pyscriptjs/src/python/pyscript/_internal.py
pyscriptjs/src/remote_interpreter.ts
pyscriptjs/tests/integration/test_py_repl.py

Currently if the result from pyExec is a PyProxy, it gets destroyed. This switches to using `to_js` to handle this (it is better to use than an explicit `create_proxy` since it automatically decides whether to create a proxy or not).
I also added `destroyIfProxy` which checks if something is a `PyProxy` and then destroys it. Each use of `pyExec` needs to call `destroyIfProxy` on the result after it is done with it.
-   [x] Add a test

Fix lifetime for pyExec results

---

.pre-commit-config.yaml
pyscript.core/esm/custom-types.js
pyscript.core/esm/index.js
pyscript.core/esm/listeners.js
pyscript.core/esm/worker/class.js
pyscript.core/test/plugins/index.html
pyscript.core/test/plugins/lua.html
pyscript.core/test/plugins/py-script.js

This MR further refines the ability for core to be extended through a `customElement` like registry where both `define` and `whenDefined` are used instead of the misleading `registerPlugin`.
Other fixes around listeners and DOM life-cycle events are in place too + manual integration tests work as expected.
* hooks defined custom "*types*" into core logic
* make `interpreter` field on a custom *type* mandatory
* bootstrap all listeners when a new *type* is defined
* automatically create `<script type="type">` and `<type-scriipt>` for HTML parity with classic PyScript
* factored out listeners + some renaming here and there beside `define` and `whenDefined`

Fix #1538 - use same customElements Registry utilities

---

pyscript.core/esm/interpreter/micropython.js
pyscript.core/esm/interpreters.js
pyscript.core/node.importmap
pyscript.core/package.json
pyscript.core/test/remote.html

This MR would like to use MicroPython from a CDN and not localhost.
* used current remote module **which does not work due missing CORS headers** ... waiting for it to be a proper CDN

Micropython via CDN

---

pyscript.core/docs/README.md

While writing documentation it became clear one of the most important topics around `XWorker` wasn't discussed at all, and this MR would like to address possible issues related to `XWorker` due missing headers from the host/server.
* added a section dedicated to *how enable XWorker* in the current docs to at least provide some guidance to our users

Added a section dedicated to XWorker required headers

---

pyscript.core/.eslintrc.json
pyscript.core/.gitignore
pyscript.core/.npmignore
pyscript.core/README.md
pyscript.core/dev.cjs
pyscript.core/package.json
pyscript.core/rollup/build_xworker.cjs

This MR goal is to build non optimized files, including the *Worker*, while watching for changes in the `./esm` folder, simplifying by far the current *core* development.
* avoid inlining as Blob the Worker content when *NO_MIN=1* is used to help developing with `debugger` or stop points in the file instead of the string
* created a simple utility that watches recursively the `./esm` folder except files triggered while building
* tested everything works as expected locally using the `npm run dev` helper

[next] Better debugging

---

pyscript.core/test/py-events.html
pyscript.core/test/py-events.py

I've messed up with the integration test and this one makes it sure both pyodide and micropython use the exact same file to orchestrate events around (when triggered).
* remove the inline scripts to orchestrate the same logic
* test everything is actually good on both interpreters

[next] Use the very same source for all Python interpreters

---

pyscript.core/esm/worker/_template.js
pyscript.core/esm/worker/class.js
pyscript.core/package.json
pyscript.core/test/error.html
pyscript.core/test/error.py

This issue partially addresses https://github.com/pyscript/pyscript/issues/1596 by forwarding errors to the main thread in a way that the Worker can naturally intercept via `onerror`.
It is still responsibility of *core* users to handle errors visually on the page, if they want, but it wasn't possible before these changes.
It is also possible, through these changes, to provide an `XWorker` on the main thread that automatically handle errors visually, so this is  required step forward to provide better errors handling in general.
* implement a super early listener for `message` that contains errors as only `data` point
* add `try/catch` all over worker evaluation and/or bootstrap
* tested manually that either JS or Python are able to forward events from a worker
-   [x] All tests pass …

[next] Better Errors - Worker

---

pyscript.core/docs/README.md
pyscript.core/package-lock.json
pyscript.core/package.json

This MR simply sketches down the most basic PyScript Next documentation I can think about ... looking forward for review, hints, suggestions, or listening what's missing.
* improved exports as esm.sh CDN doesn't like the current state
* added docs folder with the most basic README as discussed with @fpliger 

[next] PyScript Next basic documentation

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR simply lands latest so we can test `stdlib` and all other behavior in demos and whatsoever.
* bumped the version

[next] update PyScript Next to v0.1.7

---

docs/tutorials/getting-started.md

Fix minor spelling error in getting-started.
it's -> its 
-   [ ] All tests pass locally: Didn't check
-   [ ] I have updated `docs/changelog.md`: Not applicable
-   [ ] I have created documentation for this(if applicable): Not applicable

Fix minor spelling error in getting-started.md

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/test/async.html

This MR addresses [this issue](https://github.com/pyscript/pyscript/issues/1675) working on `<script>` but not on `<py-script>`.
* ensure `<py-script>` custom elements also run async code when `async` attribute is present
* update *polyscript* to latest

[next] Fix #1675 - use `async` runner in py-script too

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/plugins/error.js
pyscript.core/src/utils.js
pyscript.core/test/click.html

Fix #1680
This MR fixes uncaught errors at distance + other issues spotted while investigating the *error* issue.
* updated *polyscript* to its latest which fixes all the code indentation issues, needed to avoid issues with foreign hooks for workers too
* updated *code* to also use the very same tiny utility that apply dedent to foreign hooks and nodes (as their content) to be sure all code always starts from `0` spaces as indentation
* added bug details to [this pyodide issue](https://github.com/pyodide/pyodide/issues/3938#issuecomment-1709848457)
* added a workaround in *core* to be sure we also catch uncaught errors from Pyodide and forward these to our notification mechanism
* added @fpliger test to smoke-test everything works as expected
* fixed an unordered race condition introduced …

[next] Cumulative pre-release patches

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/error.js

After landing https://github.com/pyscript/pyscript/pull/1682 I've realized we are currently assuming the first argument of `stderr` is an instance of *Error*, but actually the `stderr` can be an explicit `string` too if used as explicit target in Python (i.e. print to stderr).
Accordingly, we need to be sure if that's the case, we still handle / show such error as expected, otherwise it'd be `undefined` in the banner.
* use `error` argument as it is, reaching `.message` if available, falling back to the `error` itself if not

[next] Follow up on stderr

---

Makefile
pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/types/core.d.ts
pyscriptjs/tests/integration/support.py
pyscriptjs/tests/integration/test_01_basic.py
pyscriptjs/tests/integration/test_02_display.py
pyscriptjs/tests/integration/test_03_element.py
pyscriptjs/tests/integration/test_async.py
pyscriptjs/tests/integration/test_py_config.py
pyscriptjs/tests/integration/test_script_type.py
pyscriptjs/tests/integration/test_shadow_root.py

This MR fixes all tests wrongly flagged as not possible or just behind the current state of affair in *core*.
* use the right dist folder to test
* change tests in a way that makes sense or use PyScript Next features
* removed any test that was testing legacy / classic deprecation (if we don't break these now ... then when?)
* patched tests that were using old expectations about global leaks
* added comments to things we need to think about in the future
* ignored more py-config related gotchas as there's something weird to fix in our test env that has nothing to do with our project or the release
* found a bug in `display.py` around SVG and `append=False` ... test works though, but there's an extra comment
* found a bug about `async` attribute that doesn't pass through `beforeAsyncRun` …

[next] improve integration tests

---

pyscript.core/index.js
pyscript.core/package-lock.json
pyscript.core/package.json

This MR adds all [suggested fields](https://github.com/jsdelivr/jsdelivr#publishing-packages) to hint CDNs where to find our entry point for `@pyscript/core` hopefully simplifying the URL to remember whenever we'd like to import it in our documentations, without needing to write the whole thing.
This issue is also related: https://github.com/pyscript/pyscript/issues/1688
* added all *recommended* fields to the package
* used a dummy `index.js` file to avoid redirect issues in *unpkg* and *esm-run*

[next] Use all jsdelivr suggested fields for CDN

---

pyscript.core/jsdelivr.js
pyscript.core/package-lock.json
pyscript.core/package.json

This MR tries to avoid the https://github.com/jsdelivr/jsdelivr/issues/18528 issue for the time being.
* explicitly point at non-existent folder structure due missing redirect in jsdelivr
* bump patch version to wait for the CDN to catch-up on this change
* confirm manually that `https://cdn.jsdelivr.net/npm/@pyscript/core@latest` ow returns, and produces, the expected result

[next] try workaround explicit for jsdelivr

---

pyscript.core/docs/README.md

This MR simply changes suggested CDN links due cent issues discovered with some CDN.
* removed `esm.sh` suggestion as it breaks in many ways after the introduction of lazy plugins
* test current suggestions actually work
* added areference HTML page with both CSS and JS included

[next] Update CDN links to avoid breaking

---

pyscript.core/rollup/plugins.cjs
pyscript.core/src/config.js
pyscript.core/src/core.js
pyscript.core/src/fetch.js
pyscript.core/src/plugins.js
pyscript.core/types/config.d.ts
pyscript.core/types/core.d.ts
pyscript.core/types/fetch.d.ts

Fix https://github.com/pyscript/pyscript/issues/1697
This MR normalizes the shared `py-config` across all scripts/tags as custom `py-script` type, bootstrapping all default plugins, unless specified otherwise, out of the box and *before* the interpreter resolves / is ready.
This MR indirectly fixes the assumption every element could've used a different config, as that was an error-prone slippery slope anyway, and it grants that on the main thread only one *py-config* would dictate the rules.
This MR still allows different workers to have a different config, with different plugins, as those won't ever interfere with each others, and each worker might, or might not, use one or more package within its own execution (virtual) environment.
Last, but not least, this MR allows worker to be sure …

[next] Bootstrap plugins directly

---

pyscriptjs/environment.yml

Adds the pexpect package to the conda environment file, which it seems is required to run the integration tests but not included on a clean install.
(Tests were working fine on my normal computer, but not on a fresh install)
<details>
<summary> Full Console Error Output </summary>
<p>
```
(/home/jglass/Documents/pyscript/pyscriptjs/env) jglass@jglass-XPS-8930:~/Documents/pyscript$ make test-integration
mkdir -p test_results
cd pyscript.core && /home/jglass/Documents/pyscript/pyscriptjs/env/bin/pytest -vv  tests/integration/ --log-cli-level=warning --junitxml=../integration.xml
Traceback (most recent call last):
File "/home/jglass/Documents/pyscript/pyscriptjs/env/bin/pytest", line 11, in <module>
sys.exit(console_main())
^^^^^^^^^^^^^^
File …
```

Add `pexpect` to environment.yml

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/exceptions.js
pyscript.core/test/error.html
pyscript.core/test/no-error.html
pyscript.core/types/exceptions.d.ts

This MR addresses the discussion made in https://github.com/pyscript/pyscript/issues/1714 and tests everything works as expected.
* add utilities to verify there is no conflict or weird / ambiguous behavior when a `<py-script>` or `<script type="py">` node has both content and either an `src` attribute or a non empty `worker` one
* tested manually everything actually works as expected
**Note** we still don't have full support for plugins and/or errors coming from workers use cases so this does not produce the same result with workers, but it's setup to do so.

[next] Errors on ambiguous/conflicting code intents

---

pyscript.core/src/stdlib/pyscript/display.py
pyscript.core/tests/integration/test_01_basic.py
pyscript.core/tests/integration/test_02_display.py
pyscript.core/tests/integration/test_03_element.py
pyscript.core/tests/integration/test_async.py
pyscript.core/tests/integration/test_event_handling.py
pyscript.core/tests/integration/test_importmap.py
pyscript.core/tests/integration/test_interpreter.py
pyscript.core/tests/integration/test_plugins.py
pyscript.core/tests/integration/test_py_config.py
pyscript.core/tests/integration/test_py_repl.py
pyscript.core/tests/integration/test_py_terminal.py
pyscript.core/tests/integration/test_runtime_attributes.py
pyscript.core/tests/integration/test_script_type.py
pyscript.core/tests/integration/test_shadow_root.py
pyscript.core/tests/integration/test_splashscreen.py
pyscript.core/tests/integration/test_stdio_handling.py
pyscript.core/tests/integration/test_style.py
pyscript.core/tests/integration/test_warnings_and_banners.py
pyscript.core/tests/integration/test_zzz_docs_snippets.py

This is mostly a global search&replace, to replace `<py-script>` with `<script type="py">`.
The vast majority of tests just works.
A small chunk of tests had to be adapted, because the following pattern is no longer valid if you use `<script>`:
```html
<py-script id="aaa"> ... </py-script>
<py-script> display(..., target="aaa") </py-script>
```
I.e., it is not possible to use a `<script>` tag as a display `target`. This makes sense, but it required a bit of tweak in some tests.
Finally, some tests works with `<py-script>` but not for `<script>`. In those cases, I created a duplicate (i.e., two tests, one using py-script and one using script) and skipped the failing one. I will investigate later and open the corresponding issues, if needed. 
The problematic tests are: …

Use `<script type="py">` instead of `<py-script>` in most tests

---

pyscript.core/.npmignore
pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/plugins/error.js
pyscript.core/test/error.html

This MR addresses the decision made in #1730 to delegate to *polyscript* some ambiguous element parsing so that:
* *polyscript* still handles `worker` related elements without bootstrapping interpreters on main ... but ...
* if the `worker` attribute exists and has some value, it throws an `Invalid worker attribute` *SyntaxError*
* if the `worker` attribute exists and it's empty, but also an `src` exists, it throws an `Invalid src attribute` *SyntaxError*
* if the `src` attribute exists and the content is not empty or it doesn't contain just comments, it throws an `Invalid content` *SyntaxError*
* if any of the previous errors is thrown, and the element is a custom one, *polyscript* passes the error to the custom type via a newly `onerror` callback
* move all expectations into …

[next] Fix #1730 - Make `worker` an empty attribute only

---

.pre-commit-config.yaml
pyscript.core/src/core.css
pyscript.core/src/core.js
pyscript.core/src/stdlib/pyscript/__init__.py
pyscript.core/src/stdlib/pyscript/util.py
pyscript.core/test/mpy.html

This MR also provide *MicroPython* as *Pyodide* alternative by reusing 100% exact same code and successfully smoke-tested in both main and workers without issues.
* the `<py-config>` is used also by `<mpy-script>` and `<script type="mpy">` so we need to improve the config story and separate the two interpreters config (follow up issue? this is a non-blocking gotcha easy to document for an RC)
* the *PyWorker* module export still exposes `pyodide` as default interpreter as that's manual JS worker instantiation but it seems sensible as default export as *MicroPython* in workers makes (so far) little sense
* I haven't tried `pyweb` module at all
* wrapped *type* and *interpreter* as `Map` and registered both using exact same code as before (some minor internal change that makes sense anyway …

[next] Add `mpy` as custom type with PyScript magic attached

---

pyscript.core/src/config.js
pyscript.core/src/exceptions.js
pyscript.core/src/plugins/error.js
pyscript.core/src/sync.js
pyscript.core/types/config.d.ts
pyscript.core/types/exceptions.d.ts
pyscript.core/types/plugins/error.d.ts
pyscript.core/types/sync.d.ts

Adds a few additional types/removes a few `any`s in:
- config.js
- exceptions.js
- plugins/error.js
- sync.js
Not critical for nor important for the `2023.09.1` release. Just a little housekeeping.
[Edit] I didn't add the [Next] prefix because Next is now Main... hope that was right!

Adding JS Types

---

pyscript.core/.npmignore
pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/config.js
pyscript.core/src/core.js
pyscript.core/src/types.js
pyscript.core/test/piratical.html
pyscript.core/test/piratical.py
pyscript.core/test/piratical.toml
pyscript.core/test/split-config.html
pyscript.core/test/worker.html
pyscript.core/types/config.d.ts
pyscript.core/types/core.d.ts
pyscript.core/types/types.d.ts

This MR re-revert needed changes to make multiple config working on current *RC* which is otherwise broken.
* revert the removal of the code putting back TS definitions
* actually fix the `type` bug spotted in the live example (it was a typo around TOML config that *prettier* didn't catch at all)
* test everything works as expected
* added the test page that was failing

[RC] Work on the reverted changes

---

pyscript.core/.eslintrc.cjs
pyscript.core/.npmignore
pyscript.core/package-lock.json
pyscript.core/package.json

Last *Friday* we had an issue due *eslint* recommendation **not spotting global leaks** in a single function and I was a bit horrified by the fact nothing was shown in console and the build went through it.
* ignore top level folders as we have pre-commit hooks there anyway as extra guard *but* actually enforce eslint checks on code and syntax for the `src` folder without enforcing styles
* test that if that `type` signature reference is out the build fails so we can sleep better at night

Fixed eslint ignoring global leaks

---

pyscript.core/src/core.js
pyscript.core/tests/integration/test_02_display.py

Fixes an error when the `target` attribute is used with `<script type="py">`. Fixes #1750 .
- Ensure that `queryTarget` is passed both the element and the selector
- Add a test (`test_tag_target_attribute`)
- Rename `test_target_attribute` (which tests `display(..., target="...")` ---> `test_target_parameter` to help distinguish the two.

Fix `target` attribute lookup on `<script type="py">`

---

pyscript.core/tests/integration/test_py_config.py

`test_intepreter_config` was passing by coincidence - we no longer use the `interpreters` key of py-config (as far as I can tell). 
Skipped this test and clarified the comments on a couple other similar ones.

Skip `test_interpreter_config`

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/test/html-decode.html
pyscript.core/tests/integration/test_01_basic.py

This MR simply removes undesired, automatically returned, `innerHTML` artifacts from the source code.
* use a long-standing minimalistic escaper to be sure unintended HTML is removed
* change smoke test to be sure everything works as expected
* un-comment the skipped test to catch further issues in the future

Fix #1764 - Unescape `innerHTML` artifacts

---

pyscript.core/src/core.js

This MR simply passes along whatever `interpreter` value was set in the `<py-config>` or `<mpy-config>` allowing anyone to test different versions of their interpreters without needing upstream changes in *polyscript*.
* pass the `version` property to *polyscript* on custom type definition (as it's tested and working in there) via the `interpreter` config field
* smoke test *polyscript* behind the scene to be sure both versions and interpreter versions match

Fix #1765 - Pass the optional config `interpreter` value

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR simply brings in the latest *polyscript* which `config` parser understands the `files` field too as discussed in https://github.com/pyscript/pyscript/discussions/1755
* update *polyscript* to its latest after testing it does what it's supposed to do

Add experimental files config parser

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/hooks.js
pyscript.core/types/hooks.d.ts

This MR brings in the [type-checked-collections](https://github.com/WebReflection/type-checked-collections#readme) module so that our hooks are now guarded to be of correct types.
This MR also adds the `onWorkerReady` hook which was missing.
* used two different typed *Set* a `function` one and a `string` one
* add logic for `onWorkerReady` as we were not exposing it before

Fix #1766 - Ensure correct hooks types

---

pyscript.core/tests/integration/support.py
pyscript.core/tests/integration/test_02_display.py
pyscript.core/tests/integration/test_py_config.py

This MR adds an easy to wait for HTML class selector on `py:all-done` event + it exports `pyConfig` and `mpyConfig` globally to let us easily test anything we'd like to test.
* leak globally `config.py` as `pyConfig` and `config.mpy` as `mpyConfig`
* use the HTML selector to be sure DOM changes are applied

Add a selector to the HTML tag + export config

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/all-done.js
pyscript.core/src/core.js
pyscript.core/test/display.html

This MR fixes an issue with `py:all-done` event by using events instead of hooks as hooks require awkward main thread orchestrations while events are always grant to land in there thanks to latest polyscript update.
* update polyscript to its latest after providing better life-cycle for events https://github.com/pyscript/polyscript/pull/54
* change entirely the whole `py:all-done` event by using those events

Improved py:all-done event

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib/pyscript/__init__.py
pyscript.core/tests/integration/test_01_basic.py

This MR simply exports stuff that used to be exported and it's also documented so that it fixes #1777.
* export all fields from `magic_js.py`
* add a test to check those exports don't throw out of the box

Fix #1777 - Export also PyWorker and current_target

---

pyscript.core/src/stdlib/pyscript/__init__.py
pyscript.core/src/stdlib/pyscript/display.py
pyscript.core/src/stdlib/pyscript/magic_js.py
pyscript.core/tests/integration/support.py
pyscript.core/tests/integration/test_01_basic.py
pyscript.core/tests/integration/test_02_display.py

This PR includes a more robust implementation of the `display` function, and appropriate exception raised. 
All changes to code are corroborated by corresponding test cases (see `tests/integration/test_02_display.py`)
In more details. 
First, the`target` parameter is checked to be of type `str` or `None`. If that's not the case, a `TypeError` exception is raised. This is in line with similar implementations in the Python language (e.g. `str.split` with an integer separator).
Then, if `target` is an empty string, a `ValueError` is raised.
Afterwards, if `target` starts with `#`, the initial `#` is removed so that the next `document.getElementById` would still be capturing the intended target. 
This change would _align_ with the default behaviour of the `@when` decorator where selector is …

FIX to display function handling null element reference, and wrong target parameter values

---

pyscript.core/src/config.js
pyscript.core/src/core.js

This MR ensure once that plugins are awaited before custom types are defined, granting somehow that plugins code can run and guarantee all hooks are actually used when custom types bootstrap.
This is needed to also eventually improve plugins support within *workers*.
* await for plugins *without* blocking current module execution so that exports are still available to plugins
* define custom elements and custom types only after all plugins have been resolved
* minor cleanup here and there, most notably removed the `_pyodide` ugly and undesired getter

Wait for plugins before defining the custom type

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR simply updates PyScript dependencies to fix a nasty bug recently investigated: https://github.com/WebReflection/coincident/issues/26
* update all dependencies
* simplified `server` with latest `static-handler` module and its `--coi` flag

Updated to latest polyscript + coincident

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/exceptions.js
pyscript.core/src/fetch.js
pyscript.core/types/core.d.ts

This MR is a follow up of the *polyscript* approach https://github.com/pyscript/polyscript/pull/59 to avoid ever dealing with multiple versions of the project in the wild, as discussed in https://github.com/pyscript/pyscript/issues/1799 + it uses the latest polyscript to also stop having issues when embedded by other tools.
* use the latest `polyscript/exports` to import all utilities and internal needed to make PyScript work
* use the same global, Symbol based, guard to avoid ever registering or bootstrapping PyScript twice, allowing multiple embedded projects to effectively share hooks too

Fix #1799 - Avoid multiple bootstraps when embedded

---

pyscript.core/docs/README.md

After discussion on https://github.com/pyscript/pyscript/pull/1807, and the new docs PR coming up here: https://github.com/pyscript/docs/pull/35 which fixes the discrepancy.
This PR fixes the documentation for `pyscript.core` regarding `append` being `True` by default in `display`

fix docs for append as True

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/hooks.js
pyscript.core/src/plugins-helper.js
pyscript.core/src/plugins/error.js
pyscript.core/test/hooks.html
pyscript.core/test/worker.html
pyscript.core/types/core.d.ts
pyscript.core/types/hooks.d.ts
pyscript.core/types/plugins-helper.d.ts

This MR brings in the latest *polyscript* version with its new [hooks](https://pyscript.github.io/polyscript/#hooks) mechanism in, providing the ability to register also callbacks for workers and code for the main thread.
* moved out of core some logic to help plugins or to simplify hooks transformation / creation
* improved async JS callbacks by actually awaiting these instead of just run all at once
* deeply tested that all ways to create a JS function can be sanitized before being passed as string
* made worker JS hooks lazy reachable with evaluation able to bring sanitized functions too

Breaking: new Polyscript Hooks mechanism

---

pyscript.core/src/core.js
pyscript.core/src/stdlib.js

This MR avoids duplicated FileSystem module pollution on main, as that's already part of the code in main hooks story and as that fails, actually rightly so somehow, in MicroPython only.
* remove the manual need to pollute the main thread with code that already runs on `codeBeforeRun` thanks to the shared dance and behavior of latest changes.

Fix #1812 - Avoid duplicated pyscript module

---

Makefile
pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib.js
pyscript.core/test/hooks.html
pyscript.core/test/mpy.html
pyscript.core/test/mpy.spec.js

This MR fixes https://github.com/pyscript/pyscript/issues/1814 by providing a very simple, fast, yet reliable test around `mpy` custom type, hooks, and display.
This MR also fixes https://github.com/pyscript/pyscript/pull/1813#issuecomment-1781502909 so that multiple MicroPython on main work now without any issue.
* copied over the same script to run integration tests
* changed smoke-test files to facilitate integration tests
* slightly changed the *stdlib* bootstrap code to fix MicroPython path issues

Fix #1814 - Basic mpy integration

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js

This MR is a quick amend for the latest PyTerminal one, as when `<py-script>` is used, instead of `<script type="py">`, the terminal is created as `undefined-terminal` due lack of `type` for the element.
As we only support *pyodide* terminal for the time being, I think this is the easiest way to support both cases without ugly names used as terminal targets.
* remove the usage of `element.type` to define the element name
* use always `py-terminal` as element name to help CSS too

Use <py-terminal> as default target

---

pyscript.core/src/stdlib/pyweb/pydom.py
pyscript.core/test/pyscript_dom/index.html
pyscript.core/test/pyscript_dom/tests/test_dom.py
pyscript.core/types/stdlib/pyscript.d.ts

This PR adds the value property to PyDom.Element and ElementCollection so that it's now possible to do:
```python
input_el = pydom[f"#some-id"]
input_el[0].value = "some value"
input_el[0].value == "some value" == input_el[0]._js.value
input_el.value = "another value"
input_el.value[0] == "another value"
```
`value` property has been added to `pydom.Element` and `pydom.ElementCollection`
-   [X] All tests pass locally
(changelog and docs change are coming as a follow up PR in the right repo)

Value property to PyDom.Element and ElementCollection

---

pyscript.core/src/plugins/py-terminal.js
pyscript.core/tests/integration/support.py
pyscript.core/tests/integration/test_01_basic.py
pyscript.core/tests/integration/test_py_terminal.py

This MR goal is to stop PyScript execution if more than a terminal is present on the page, as we're still discussing what should happen there or even *if* it should.
* import *error* plugin to notify on the page something is wrong
* throw regardless to "*stop the world*" hence avoid any further parsing of multiple terminals
* update integration tests so that it's clear the error is shown

Fix #1834 - Throw an error if more than a terminal exists

---

pyscript.core/src/plugins/py-terminal.js
pyscript.core/test/py-terminal.html
pyscript.core/tests/integration/test_py_terminal.py

This MR specifically addresses [this comment](https://github.com/pyscript/pyscript/pull/1816#discussion_r1378085503) and while everything seems to be fine I'd love to have @hoodmane or @antocuni reading the changes and tell me if this is the best way forward, thank you!
* drop the Python `builtins.input = ...` workaround and use Pyodide directly
* update the smoke-test page to be sure everything is fine

PyTerminal: use Pyodide instead of Python

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js
pyscript.core/test/py-terminal.html
pyscript.core/tests/integration/test_py_terminal.py

This MR fixes https://github.com/pyscript/pyscript/issues/1840 by not bootstrapping users into an interactive shell by default.
* remove the Python hook that bootstraps the interactive shell
* comment out the integration test without removing the test as that will be helpful later on
* updated the smoke test with a listener after the code that will still run without issues when `worker terminal` attributes are used

Fix #1840 - Do not bootstrap interactive shell

---

pyscript.core/src/hooks.js
pyscript.core/test/input.html
pyscript.core/tests/integration/test_01_basic.py

This MR fixes https://github.com/pyscript/pyscript/issues/1841 by providing a better error when `input` is used on the main thread.
* add a main `codeBeforeRun` hook that raises an error when no worker is used
* smoke-test both pyodide and micropython
* add an integration test to validate expectations (input is tested in workers too so it skips the worker test as it's pointless)

Fix #1841 - Provide a better error when input is used

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/rollup/3rd-party.cjs
pyscript.core/src/plugins/py-terminal.js
pyscript.core/types/3rd-party/xterm_addon-fit.d.ts

This MR tries to fix https://github.com/pyscript/pyscript/issues/1861 by using an [addon](https://github.com/xtermjs/xterm.js/tree/master/addons/addon-fit) that makes the text fit into as much available space as possible, removing truncation at X cols.
* pre-fetch the add-on on build time
* bootstrap the addon after opening the element in a terminal

Fix #1861 - Use addon to fit lines instead of truncating

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR updates Polyscript to its latest, bringing in latest *coincident* `Symbol.for('...')` capability and the `[js_modules.main/worker]` config parser goodness.
* updated Polyscript to its latest

Updated Polyscript to its latest

---

pyscript.core/src/stdlib/pyscript/magic_js.py
pyscript.core/test/worker.py

This MR solves the discussion we had in https://github.com/pyscript/pyscript/discussions/1878 by attaching to the worker `js` module the document from main out of the box.
* when running in worker, patch the `js` module with a document
* smoke-test everything works as expected

Patch js.document out of the box

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/test/multi.html

This MR fixes an issue when both `mpy` and `py` scripts (or related tags) live on the same page / main thread + it reduces possible conflicts around the `currentScript` exposed via our own module.
* move within the *for loop* all variables that should **not** be shared among interpreters
* test that everything actually works as expected
* fix typo in *PyWorker* description

Reduce conflicts on multiple custom scripts

---

pyscript.core/src/plugins/py-terminal.js

This MR solves the fact the XTerm reference used by any `py-terminal` is not exposes, hence it's hard to fully interact with it, or customize it.
* attach to the `<py-script terminal>` or `<script type="py" terminal>` the *terminal* reference
* test live that `script.terminal.clear()` works as expected

PyTerminal - expose the reference through the element

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib/pyscript/magic_js.py
pyscript.core/test/js_modules.html
pyscript.core/test/js_modules.js
pyscript.core/test/mpy.spec.js

This MR fixes https://github.com/pyscript/pyscript/issues/1899 by registering a fake `pyscript.js_modules` within the *stdlib* so that both imports are valid:
```python
from pyscript import js_modules
js_modules.xxx
from pyscript.js_modules import xxx
```
* update all dependencies to have latest *polyscript* in
* register an explicit `pyscript.js_modules` as *sys* module
* register all known sub-modules as explicit `pyscript.js_modules.xxx`
* add integration + smoke test to be sure all ways to import JS modules work

Fix #1899 - Expose pyscript.js_modules as module

---

LICENSE

Our license file was missing the copyright and attribution section
Add the missing info, aligning to the file we have in pyscript.core

Add correct copyright and attribution to main license file

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js

This MR fixes https://github.com/pyscript/pyscript/issues/1939 by adding a generic interpreter `stderr` handler when a terminal is bootstrapped in either the main or the worker thread, fixing a regression recently introduced by bootstrapping the terminal only via Pyodide API.
* provided the right `io.stderr` to both main and worker
* smoke test everything is fine

Instrumented the `io.stderr` too when terminal exists

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js
pyscript.core/src/sync.js
pyscript.core/test/mpy.spec.js
pyscript.core/test/py-terminal-worker.html
pyscript.core/test/py-terminals.html
pyscript.core/tests/integration/test_py_terminal.py
pyscript.core/types/sync.d.ts

As discussed with both @ntoll and @JeffersGlass, we'd love to be able to have multiple terminals on a page through *worker* attribute, as these are all fresh-new bootstrapped interpreters, these can be interactive too and any constraint regarding the *main* thread can be easily avoided / ignored.
This MR makes it possible to use 1, 2, or any amount of `<script type="py" worker terminal>` on the same page, being these either bootstrapped all at once or incrementally (dynamically).
* added a shared `sync.is_pyterminal()` utility to understand within hooks if the *xworker* is actually meant to be used as *terminal* or it's just a regular worker. By default that returns `false` but bootstrapped workers will have it returning true
* moved the worker related (and then stringified) hook in the …

Multiple Worker based Terminals

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-editor.js
pyscript.core/test/multiple-editors.html

This MR fixes https://github.com/pyscript/pyscript/issues/1946 by not holding while looping to activate editors.
Here a basic, pseudo code, representation of the issue that is solved:
```js
async function init() {
for (const script of document.querySelectorAll("script[type='editor']")) {
// here the script type is changed to avoid being part of this loop
script.type += '-activated';
// but if in here we hold anything async ...
await bootstrap(script);
// the loop will execute before giving a chance to other, already discovered,
// scripts to initialize themselves and get a new `type`
}
}
// one call ASAP
init();
// MutationObserver calls triggered by first script bootstrap
init();
// any other reason to call init again
init();
```
As summary, this MR fixes in one single loop the type and …

Fix #1946 - Do not hold while bootstrapping

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR brings in latest polyscript version with `experimental_create_once` config feature that could, only if present, change the way *Pyodide* on the main thread behaves and help us better analyze or measure the performance or memory impact of such flag, if ever enabled, to eventually use that data to convince *Pyodide* team that's a way forward too.
* update *Polyscript* to its latest

Update Polyscript to its latest w/ experimental

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR brings in latest [polyscript](https://github.com/pyscript/polyscript) with latest [coincident](https://github.com/WebReflection/coincident) which include a fix for an uncanny situation presented when heavy modules (i.e. pandas) interrupt the code execution in an *async* + *worker* environment / context.
The culprit of the issue is that in some circumstance the *FinalizationRegistry* could've run **after** the related *WeakRef* already dropped the retained reference so that the map would've held only the *WeakRef* but not its desired value.
In **coincident** this has been fixed by re-observing the value with a different new entry so that previous WeakRef can go while the ultimately needed one will provide the desired functionality.
* updated both polyscript and coincident to their …

Update polyscript + coincident to their latest

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/stdlib/pyscript/magic_js.py
pyscript.core/test/no_sab/index.html
pyscript.core/test/no_sab/worker.py
pyscript.core/types/core.d.ts

This MR is a follow up integration of https://github.com/pyscript/polyscript/pull/80
Beside fixing the exported *JS*' `PyWorker`, which was fully broken and not smoke-tested properly, these changes allow the usage of PyScript in workers without *DOM* primitives or mechanism that requires synchroonus worker -> main operations, still allowing the worker code to expose, via `pyscript.sync`, any utility / callback that can be then consumed via the *main* thread only asynchronously.
```html
<script type="module">
import { PyWorker } from '@pyscript/core';
const { sync } = await PyWorker(
'./worker.py',
{ config: { sync_main_only: true } }
);
console.log(await sync.utility(3));
// log: 6
</script>
```
```python
from pyscript import sync
def utility(num):
return num * 2
sync.utility = utility …
```

Allow Workers w/out SharedArrayBuffer

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/types/core.d.ts

This MR simply brings in latest polyscript where the `try/catch` for the *SharedArrayBuffer* happens only **after** the config has been fully resolved and never before (as it was in 0.7.0 🤦).
This does not affect the procedural worker but it does affect other means to pass along a config, especially the URL and the manual JSON one.
The related *polyscript* MR, if interested: https://github.com/pyscript/polyscript/commit/35da4422facbcbdc2476b8a9170ab4272ac1fe7f
* check the flag **after** the config has been fully parsed, not before
* test that everything now works as expected

Update polyscript to fix a try/catch issue

---

pyscript.core/src/stdlib/pyweb/ui/elements.py
pyscript.core/test/ui/demo.py

This PR is just a small one for tweaks to the visual on the demo page:
- added a `main` element so we can have a main and divs inside them
- added styling for the main section
- Added cursor: pointer to left section

Small tweaks to main demo page

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib.js
pyscript.core/types/3rd-party/codemirror.d.ts
pyscript.core/types/3rd-party/codemirror_commands.d.ts
pyscript.core/types/3rd-party/codemirror_lang-python.d.ts
pyscript.core/types/3rd-party/codemirror_language.d.ts
pyscript.core/types/3rd-party/codemirror_state.d.ts
pyscript.core/types/3rd-party/codemirror_view.d.ts

This MR fixes https://github.com/pyscript/pyscript/issues/1974 by explicitly setting `utf-8` as text encoding.
**Please ignore TypeScript entries** as these were a leftover from another version and should not affect the project at all.
* apply the suggested and tested patch from the issue

Fix #1974 - Use utf-8 encoding to bootstrap stdlib

---

pyscript.core/src/stdlib/pyscript/__init__.py
pyscript.core/src/stdlib/pyscript/fetch.py
pyscript.core/test/fetch.html
pyscript.core/test/mpy.spec.js
pyscript.core/types/stdlib/pyscript.d.ts

This MR fixes https://github.com/pyscript/pyscript/issues/1993 by providing the described API.
* create a `fetch.py` file in our stdlib folder
* expose such `fetch` utility through our stdlib
* test that both Pyodide and MicroPython work as expected via integration tests

Fix #1993 - Expose a handy fetch API

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR brings in latest MicroPython with its PATH and PATH_FS back from Emscripten API and an even better support for Promise related tasks in the mixed JS <-> Python scenario.
* update polyscript with the latest MicroPython
* tested everything is good

Update MicroPython to its latest

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR brings in both MicroPython and Pyodide ability to unpack `.tar.gz` and `.zip` files out of the box in the wild via its Virtual FileSystem.
* update polyscript to its latest
* test all the things

Update Polyscript with its latest untar.gz and unzip abilities

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib/pyscript/ffi.py
pyscript.core/test/ffi.html
pyscript.core/test/index.html
pyscript.core/test/mpy.spec.js
pyscript.core/types/stdlib/pyscript.d.ts

After updating to latest MicroPython we needed to find a better story for the `ffi` utilities because `pyodide` namespace is gone (for good) in MicroPython side of affairs.
This MR exposes our own `ffi` namespace with currently the following 2 utilities:
* a `to_js` utility to convert Python references to JS counterparts, where by default dictionaries in Python are converted as *object literals* (and **not Map**) in JS
* a `create_proxy` utility for other cases where callbacks need to explicitly "*leak*" until some further condition happens (listeners or other things not automatically destroyed once executed)
* add our own `pyscript.ffi` module that exports `pyodide.ffi.to_js` with a default `dict_converter=Object.fromEntries` and `pyodide.ffi.create_proxy` as is + `jsffi.to_js` and …

pyscript.ffi - expose most essential utilities

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/plugins/py-editor.js
pyscript.core/test/py-editor/config.toml
pyscript.core/test/py-editor/index.html
pyscript.core/test/py-editor/task1.py
pyscript.core/types/core.d.ts

Fixes https://github.com/pyscript/pyscript/discussions/1997
- - -
This MR should fully solve this discussion https://github.com/pyscript/pyscript/discussions/1997 by providing, from *core* itself, our *stdlib* within the *PyEditor* custom type (both `py-editor` and `mpy-editor`).
All concerns are likely premature as users never had a chance to use our module in there, so this is a starting point that still will require some documentation update.
* use a `codeBeforeRun` hook that executes on XWorker bootstrap once and includes our stdlib artifact, as that's exactly what any other PyScript tags uses anyway
* add a check for `config` attribute, and, if there:
* if no *env* was specified, use that *config*
* if an *env* was specified and known:
* if the env had a *config*, throw an …

Fix #1997 - Bring pyscript stdlib to the PyEditor

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js
pyscript.core/test/py-terminal.html

This MR fixes https://github.com/pyscript/pyscript/issues/2002 by **not** using *tty* as it looks like XTerm is not fully compatible with that.
This MR also fixes the previous (ugly) attempt to ignore `linebuffer` in MicroPython.
It is now based on [latest polyscript](https://github.com/pyscript/polyscript/pull/91) which switched from `linebuffer` `true` (default) to `linebuffer` `false` and it's now working as expected without weird duplicated output or impossible to define multiline code.
* force Pyodide to use `isatty: false` due issues with XTerm when full *tty* is expected
* update *polyscript* to its latest
* refactor the whole code around MicroPython within the terminal
* smoke test everything is fine with multi-line definitions, errors, both interactive and not
-   [x] All tests …

Better MicroPython Terminal

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js
pyscript.core/test/py-terminal.html

This MR solves even more gotchas with MicroPython editor by providing an `input("...")` builtin utility that just works and by passing the output directly to the terminal whenever processed (the `time.sleep(1)` use case).
* move the `pyterminal_write` utility where it belongs
* create a builtin `input` function that simply returns whatever `pyterminal_read` returns
* test all cases are covered

Provide input("") and sync output to MicroPython

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js

This MR simply adds the global builtin `input(...)` utility even when `import code; code.interact()` is not used within the code, effectively behaving just like Pyodide when it comes to `input(...)` usage.
* move the `input` builtin monkey patch regardless of the *REPL* use case
* test everything is fine

Allow MicroPython input("...") to work beside the code.interact()

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-editor.js
pyscript.core/src/plugins/py-terminal.js
pyscript.core/test/py-terminal.html

**Ready to land**: this MR is the best we can do to offer unicode sequences in MicroPython.
The [underlying issue](https://github.com/micropython/micropython/issues/14255) is likely bigger than just `replProcessChar` exposed API and it should be tackled upstream but meanwhile we can at least explain that typing emoji or non ASCII chars might fail but that having these already in the output or the external file *or* asking for any input works.
Accordingly, if anyone would like to review it I think this should land sooner than later.
P.S. this has been already published as latest *npm* package.
- - -
This MR tries to tackle the fact that MiroPython doesn't really like unicode chars.
The irony lands in a simple `print("µpython")` neither the Linux REPL nor the PyScript one are able to handle …

Fix MicroPython badly handling unicode chars

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-terminal.js

This MR allows PyTerminal users to actually process imperatively some code which is something overly cumbersome otherwise within both interpreters, as these are orchestrated in a worker and not so easy to reach as both are constantly blocked due readline holding them on main.
* expose an utility to `process(code)` where each line is simulated as pasted on the terminal
* verify everything works as expected

PyTerminal .process(code) utility

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/rollup/3rd-party.cjs
pyscript.core/src/plugins/py-terminal.js
pyscript.core/types/3rd-party/xterm_addon-web-links.d.ts

This MR automatically link well formed URLs just like a regular shell would do.
* added `@xterm/addon-web-links` as lazy loaded terminal dependency
* tested everything is fine

Added @xterm/addon-web-links to the terminal

---

pyscript.core/src/core.js
pyscript.core/src/hooks.js
pyscript.core/src/stdlib.js
pyscript.core/types/core.d.ts
pyscript.core/types/hooks.d.ts
pyscript.core/types/stdlib.d.ts

This MR goal is to unlock https://github.com/pyscript/pyscript/pull/1960 issues with MicroPython currently being unable to deal with too much code to `run` at once: see https://github.com/micropython/micropython/issues/14307
* created an ad-hoc solution that is the least obtrusive around our stack, so that we can fine-tune what's undesired on specific target side (in this case the `mpy` custom type)
* test results are satisfying all over the place

Avoid PyWeb as part of stdlib on MicroPython

---

pyscript.core/src/stdlib/pyscript/display.py

While working on our own documentation I've realized that the current `HTML` class utility is not working on *MicroPython* due a `reversed(...)` call that does not exist in there.
* reverse mime types manually
* remove the need to call `reversed(...)` later on

HTML class in MicroPython

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib/pyscript/__init__.py
pyscript.core/src/stdlib/pyscript/magic_js.py
pyscript.core/test/config-url.html

This MR fixes https://github.com/pyscript/pyscript/discussions/2040 by providing a `config` entry in the *pyscript* module.
/cc @ntoll 
* updated *polyscript* to its latest which augments custom scripts on both *main* and *worker* with an extra `config` object literal
* change the *pyscript* `stdlib` to provide a *Pythonic* version of such config instead
* test via integration both *main* and *worker* scripts get the config and can introspect it
-   [x] I have created documentation for this(if applicable) - **documentation** actually on *polyscript* side

Fix #2040 - Polyscript update to provide config dictionary

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/plugins/py-editor.js

This MR addresses the [concern exposed in Discord](https://discord.com/channels/972017612454232116/972020206538997822/1235662529447858288) where indeed the `interpreter` *config* property gets fully ignored when present.
* pass along the `version` to bootstrap the right interpreter when defined as such in the `config` file

Fixed py-editor offline use case

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib/pyscript/websocket.py
pyscript.core/test/ws/index.html

This MR adds a feature to pass `onopen`, `onmessage`, `onerror` and `onclose` listeners directly to the web socket once it gets initialized.
* optionally accepts `onopen`, `onmessage`, `onerror` and `onclose` as *kw* arguments and directly set this while initializing the web socket
* test everything is fine

Added listeners to the constructing kw options

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR fixes https://github.com/pyscript/pyscript/discussions/2067 by using the latest *polyscript* which allows MicroPython to handle `.whl` packages (or files).
* update *polyscript* to its latest

Fix #2067 - Enable .whl packages

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/core.js
pyscript.core/src/stdlib/pyscript/__init__.py
pyscript.core/src/stdlib/pyscript/magic_js.py
pyscript.core/test/py_modules.html

This MR forwards from *polyscript* the `lazy_py_modules` utility as `pyscript.py_import` and it offers a 1:1 API for *JS* via `pyscript.js_import`.
* expose `polyscript.lazy_py_modules` as `pyscript.py_import`
* expose on both main and workers `pyscript.js_import` to land runtime JS modules on the main thread (usable from workers too)
* test everything works just fine (integration tests in *polyscript* already for the `py_import` story)

Expose pyscript.py_import and js_import for lazy Python/JS modules

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/stdlib/pyscript/event_handling.py
pyscript.core/src/stdlib/pyweb/__init__.py
pyscript.core/src/stdlib/pyweb/media.py
pyscript.core/src/stdlib/pyweb/pydom.py
pyscript.core/src/stdlib/pyweb/ui/__init__.py
pyscript.core/src/stdlib/pyweb/ui/elements.py
pyscript.core/test/pydom.py
pyscript.core/test/pyscript_dom/tests/test_dom.py
pyscript.core/tests/integration/test_pyweb.py
pyscript.core/types/stdlib/pyscript.d.ts

This MR brings back files from the commit b41cfb7b60675d2ed89b6517019a7f0930fe6816 without removing current WIP so that we should be able to both move forward and release until the moving forward is completed.
In few words, this reverts this commit: https://github.com/pyscript/pyscript/pull/2092 without affecting anything else.
* bring back the old `pyweb` folder
* bring back previous tests too

Bring back pyweb as it was

---

pyscript.core/package-lock.json
pyscript.core/package.json
pyscript.core/src/config.js
pyscript.core/src/core.js
pyscript.core/src/plugins/py-editor.js
pyscript.core/src/plugins/py-terminal.js
pyscript.core/test/py-editor/index.html
pyscript.core/types/config.d.ts
pyscript.core/types/core.d.ts
pyscript.core/types/exceptions.d.ts

This MR fixes https://github.com/pyscript/pyscript/issues/2109 by centralizing the `config` from `location` across all places plus enabling *JSON* as inline config for the PyEditor.
* refactored all `new URL(..., location.href).href` into a single, always same, yet shared, utility
* verified everything works as expected

Fix #2109 - Allow inline JSON config attribute in PyEditor

---

pyscript.core/src/stdlib/pyscript/web/elements.py

video.snap and canvas.download methods used an obsolete method (self.create). They don't anymore.
Replace use of create with call to the appropriate Element instance e.g. self/create("canvas") -> canvas())

fix: broken methods video.snap and canvas.download

---

pyscript.core/package-lock.json
pyscript.core/package.json

This MR brings in the latest *polyscript* **AS IS** and it just updates Pyodide to its recent 0.26.2 release.
For reference: https://github.com/pyscript/polyscript/commit/6e981f5902f7f61906434044e0a3b07037295f97
* update polyscript that was updated to have latest pyodide

Update Pyodide to its 0.26.2 version

---

pyscript.core/src/plugins/py-editor.js
pyscript.core/test/issue-2093/error.js
pyscript.core/test/issue-2093/index.html
pyscript.core/test/mpy.spec.js

This MR fixes https://github.com/pyscript/pyscript/issues/2093 .
Because a `setup` node doesn't have a related element to show eventually failures, issues in `setup` code were not spotted at all.
Now the `notify` is used but if the `error` plugin has been disabled, or its node made invisible, at least something is shown in the console.
* use the `notify(msg)` utility like we do in other places
* test that failing setup nodes pass through such utility
* since we are here ... a `setup` node now also logs if any `print` statement is used in there

Fix #2093 - Show setup errors with the editor

---

pyscript.core/src/stdlib/pyscript/event_handling.py

In *Pyodide* (only) use case when a function has no args but it's `async`, the `wrapper` is not asynchronous and it doesn't *await* the passed callback. This results into hard to understand errors otherwise not present in MicroPython.
This MR fixes that by using the right *introspection* to decide how the *wrapper* should be defined (that is: either async or sync).
* define an `async` wrapper when the given function is *async* too
* test all conditions (manually) that everything works:
* test `async def click()` and `async def click(event)` after `@when`
* test `def click()` and `def click(event)` after `@when`

Avoid throwing if Pyodide does not await due missing arguments

---

pyscript.core/src/plugins/py-editor.js

This is just a followup for this MR https://github.com/pyscript/pyscript/pull/2151 and it uses the right tool for the job, making the code also more consistent across JS/Python code.
* use `insertAdjacentHTML` instead of `innerHTML +=`
* test everything works fine
PyEditor test:
```python
i = 0
while i < 5:
i = i + 1
print(i)
import asyncio
await asyncio.sleep(1)
print(shenanigans)
```

Follow up - Remove all innerHTML += for consistency sake

---

pyscript.core/tests/js_tests.spec.js

The "MicroPython + workers" JavaScript test **sometimes** times out when running in CI. This is because PyScript is starting 2 MicroPython and 2 Pyodide workers, which can be processor and resource intensive (and thus slow).
This PR increases the timeout for this test to 2 minutes. If it doesn't complete by then, there's definitely a problem.

Increase timeout for heavy-load test.

---

pyscript.core/package.json

In our continuing question to figure out why CI resources appear to affect our test run, we're trying to make our tests run sequentially, one at a time.
Playwright runs with only one worker.

Only use a single worker for playwright tests.

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
.github/workflows/publish-unstable.yml

The `sed` based search/replace used for generating a static web page with all the details for a specific release of PyScript, was slightly broken.
Reorder the search and replace so everything works.
-   [x] I have created / updated documentation for this (if applicable)

Fix sed search/replace when creating static page for a specific PyScript release.

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
.github/workflows/publish-unstable.yml

I am incapable of reproducing any issue other flows around publishing have hence I'd like to see if by using just the same machine we use to test, build, and validate our code would solve the issue around builds with a single core, also assuming our projects with *workers* inevitably needs multi-core targets, which is the norm.
Use the same machine we use for CI
-   [ ] I have created / updated documentation for this (if applicable)

Use ubuntu-latest-8core everywhere

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
.github/workflows/publish-unstable.yml
.github/workflows/test.yml

With this MR https://github.com/pyscript/pyscript/pull/2196 we managed to fix flaky tests that were impossible to reproduce locally after dozen consecutive runs but it's not clear why standard *ubuntu-latest* would fail so I'd like to find out worker boundaries with this MR that:
* if it works out of the box, should be tested with other flows that used to fail before
* as we improved already testing time and required dependencies, we might as well use a larger worker but the minimum possible needed otherwise we're paying (each minute) for something that is not fully used (we use 2 workers for playwright) and it might not even bring performance benefits
* as in CI we run a lot the flow, if the overall time is still under 3 minutes and nothing ever fail, I think we'd be better with a less …

Try to find out what we really need in CI

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
.github/workflows/publish-unstable.yml
.github/workflows/test.yml

Reverted 4core because our tests require more cores to run in parallel by math.
* reverted 4core ... we're back to 8
-   [ ] I have created / updated documentation for this (if applicable)

Back to 8 cores

---

README.md

The link to `core/README.md` was never correct.
Ensures the link is now correct.
-   [X] All tests pass locally
-   [X] I have created / updated documentation for this (if applicable)

Fix broken link to core/README.md in the root README.

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template needed updating in light of recent refactoring.
* Update language to make it more accurate about what the committer needs to have run (`make build` and `make precommit-check`).
* Add an item to ensure the committer has run/fixed the result of `make precommit-check`.
* Minor simplification of language.
-   [X] All tests pass locally
-   [X] I have created / updated documentation for this (if applicable)

Update/simplify our PR template.

---

core/package-lock.json
core/package.json
core/src/plugins/donkey.js
core/tests/manual/donkey/index.js
core/types/core.d.ts
core/types/plugins/donkey.d.ts

This MR goal is to satisfy latest @JoshuaLowe1002 requirement around the *donkey* functionality, so that if not available both `clear` and `reset` methods now terminate the worker and terminal and re-bootstrap the whole thing.
Everything else works as before *except* both `clear` and `reset` are now async, letting `kill` be the only synchronous method out of exposed utilities.
* if the donkey is working and `clear` or `reset` are invoked, "*kill previous terminal and farmer*" and bootstrap again
* if the donkey is not working, simply try to invoke `clear` or `reset` as it was before
* change the manual test to be sure everything works as expected

Donkey clear and reset now terminate when busy

---

Makefile

The `make update` command broke the JS dependencies (thanks to `npm update`).
Update `make setup` and `make update` to use `npm ci` (in setup) and remove `npm update` (in update).
-   [x] I have created / updated documentation for this change (if applicable).

Fix Makefile so JS dependencies don't get into a bad state.

---

core/package-lock.json
core/package.json

This MR fixes https://github.com/pyscript/pyscript/pull/2065 by updating Polyscript after https://github.com/pyscript/polyscript/pull/124 landed.
* update Polyscript to its latest

Fix #2065 - Allow usage of index_urls for Pyodide

---

core/package-lock.json
core/package.json
core/src/plugins/py-terminal/mpy.js

While testing latest `@xterm/xterm` I've noticed that *mpy* terminal, when is not in a REPL, throws errors due usage of something not exported via `sync` before the `code.interact()` is eventually invoked/used.
* export a noop by default
* test everything is fine with or without the REPL around

Fixed MicroPython error on non-worker terminal

---

core/package-lock.json
core/package.json
core/src/plugins/donkey.js

This MR fixes an issue encountered by @JoshuaLowe1002 where the `__terminal__` special variable is not exposed if the *donkey* is not persistent.
* add a `__terminal__` reference when `terminal` option is present and the `persistent` one is not *True*
* test everything works as expected

Added __terminal__ in non-persistent donkey

---

core/src/plugins/donkey.js

Enables the service worker attribute for the donkey worker plugin to allow the [service worker operation mode](https://docs.pyscript.net/2024.8.2/user-guide/workers/#option-2-service-worker-attribute) 
- Add `serviceWorker` option to enable `service-worker` attribute in donkey plugin

Enable service-worker attribute for donkey worker

---

core/package-lock.json
core/package.json
core/src/plugins/py-game.js
core/tests/manual/game/index.html

This MR fixes an issue with not fully resolved URLs as `config` attribute + it patches the `builtins.input` function to avoid surprises, using the native `js.prompt` function as least surprise/solution.
* enforced fully qualified *url* resolution for the config, when it's known
* patched `input` so that it's usable as it's common for games to ask for inputs

PyGame - TOML + JSON absolute URL + input patch

---

core/src/core.js
core/src/zero-redirect.js

This MR fixes https://github.com/pyscript/pyscript/issues/2326 by simply avoiding users to visit directly `http://0.0.0.0` as:
* most browsers refuse to even visit that address anyway (Windows)
* Firefox redirects automatically to `127.0.0.1` for loopback
* the `0.0.0.0` is not really an address and nothing on the Web can reach that address
So with this simple check that error people using `python -m http.server`, which hints to reach that broken address by default, will be redirected to `localhost`.
* add a top-level import that triggers a redirect if the address is wrong

Fix #2326 - Redirect to localhost when on 0.0.0.0

---

public/index.html

The code example in the template for the release page uses HTML comments rather than Python comments between the `<script>` tags. Unsurprisingly, this causes syntax errors if you actually try to cut and paste the example into actual code.
Change the HTML comments into equivalent (and thus syntactically correct) Python comments.
-   [x] I have created / updated documentation for this change (if applicable).

Fix code example problem in the release HTML.

---

.prettierignore
bridge/README.md
bridge/index.js
bridge/package.json
bridge/test/index.html
bridge/test/remote/index.html
bridge/test/sys_version.py
bridge/test/test.js
bridge/test/test.py

As demoed today (and cleaned up after) it is possible to make it easy to import *Python* utilities from a *JS* module with the only constraint that `any_file.js` has at its same position `any_file.py` to help publishing or shipping *Python* modules that can be easily consumed via *JS* / 3rd party scripts.
This MR would like to create a specific folder that is not coupled with *PyScript* release cycles as it won't likely change much in the future but it deserves its own module/namespace (imho) so here I am with this proposal.
-   [ ] I have checked `make build` works locally.

The PyScript Bridge Helper

---

bridge/README.md
bridge/index.js
bridge/package.json
bridge/test/test.js

This MR simply improves what I've brough in before in a better way for both developers and production use cases.
* added a `pyscript` property that indicates the exact version of *PyScript* to use (a release number). The default is still our *developers' channel* but at least it's possible now to instead pin-point a precise release (better / suggested)
* tested everything is fine with or without that property
* updated the `package.json` to publish on *npm* **only the index.js** file

Follow up on autostart
