- README.md
updated the script location in the README temporarily to point to the hosted file
> update script and css location temporarily

- README.md
append "s" for 3rd person singular
> Update README.md: fix typos

- CODE_OF_CONDUCT.md
Add a CoC file here so the governance CoC is discoverable.
> Create a code of conduct file

- pyscriptjs/examples/numpy_canvas_fractals.html
Just a simple typo in one of the flex properties.
> CSS property type

- pyscriptjs/examples/antigravity.html
- pyscriptjs/examples/numpy_canvas_fractals.html
- pyscriptjs/examples/repl.html
- pyscriptjs/examples/repl2.html
- pyscriptjs/examples/simple_clock.html
- pyscriptjs/examples/todo-pylist.html
- pyscriptjs/examples/todo.html
This PR is for this issue: #87.
> Fix absolute path when import `.py` files in examples

- README.md
Instead of square brackets, parentheses should be used.
> Get the GETTING-STARTED link work

- GETTING-STARTED.md
- pyscriptjs/examples/toga/README.md
> Fix some typos in docs

- .github/workflows/build.yml
- .github/workflows/lint.yml
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-node/releases
> Upgrade GitHub Actions

- pyscriptjs/src/interpreter.ts
Hi,
This PR fixes some attributes in `OutputCtxManager` and `OutputManager` to set values correctly.
> Fix attributes to set values correctly

- pyscriptjs/src/utils.ts
Hi,
This PR adds some missing type annotations in utils.
> Add missing type annotations

- GETTING-STARTED.md
I added a link to help users download chrome browser.
I added the pyodide link the right way for readability.
> Added Chrome links and embedded Pyodide

- pyscriptjs/examples/simple_bioinformatics_tool.html
Dear PyScript Team!
I have developed a very simple [bioinformatics](https://en.wikipedia.org/wiki/Bioinformatics) tool, which includes `simple_bioinformatics_tool.html`. _Basically, it enables any researcher to play around with DNA seq and get the desired output (in a biological manner)._ 
Hope the example helps first-comers to PyScript while dealing with user inputs and also welcomes the bioinformatics / computational biology communities for their applications!
**Demo**: https://furkanmtorun.github.io/trial/simple_bioinformatics_tool.html
**Inspired from:** https://www.bioinformatics.org/sms/rev_comp.html
**Screenshot**:
Best,
Furkan
> ADD: Simple Bioinformatics Tool 

- .pre-commit-config.yaml
Also fixes an issue where `check-yaml` was being run twice.
> pre-commit: Try to autofix yaml BEFORE checking it

- GETTING-STARTED.md
> Changed wallis to computepi for better description

- README.md
Made minor changes to the README to fix a few grammar errors and to improve some sections that weren't reading too well.
> README wording improvements

- .github/workflows/build.yml
- .github/workflows/lint.yml
Node.js 12 is end-of-life.  https://nodejs.org/en/about/releases
> GitHub Actions: Test on current Node.js

- pyscriptjs/src/components/pybutton.ts
Hi,
This PR fixes some ESLint warnings related to `any`.
> Fix ESLint warnings

- pyscriptjs/src/App.svelte
- pyscriptjs/src/components/pyscript.ts
`newEnv` does not seem to be reassigned elsewhere, so it looks like it's safe to use `const` instead of `let`.
Also refactored an `if` statement with a logical OR expression, as I believe it reduces the lines of code without sacrificing readability.
> Change let to const; Minor code improvement

- pyscriptjs/examples/altair.html
- pyscriptjs/examples/antigravity.html
- pyscriptjs/examples/bokeh.html
- pyscriptjs/examples/bokeh_interactive.html
- pyscriptjs/examples/d3.html
- pyscriptjs/examples/folium.html
- pyscriptjs/examples/handtrack/say_hello.html
- pyscriptjs/examples/hello_world.html
- pyscriptjs/examples/mario/play_mario.html
- pyscriptjs/examples/matplotlib.html
- pyscriptjs/examples/micrograd_ai.html
- pyscriptjs/examples/numpy_canvas_fractals.html
- pyscriptjs/examples/panel.html
- pyscriptjs/examples/panel_deckgl.html
- pyscriptjs/examples/panel_kmeans.html
- pyscriptjs/examples/repl.html
- pyscriptjs/examples/repl2.html
- pyscriptjs/examples/simple_clock.html
- pyscriptjs/examples/toga/freedom.html
Give examples an absolute link to alpha css and js files.
> redirect examples

- pyscriptjs/src/interpreter.ts
Matches on minified and unminified script.
> Ensure minified pyscript is captured by query selector

- .github/workflows/build-alpha.yml
CI should only run on merges into main branch.
> Build on main branch tags only

- pyscriptjs/examples/readme.md
Added Pyscript example link to example folder.
You can also add a description and a link to [the Pyscript website](https://pyscript.net/) in the about section.
> Pyscript example link

- docs/concepts/what-is-pyscript.md
- docs/conf.py
- docs/environment.yml
- docs/tutorials/getting-started.md
@fpliger If you could please assist in the defining those visual tags and py-repl that would be much appreciated.
Also, the video I'm embedding is here: https://www.youtube.com/watch?v=ZtC7TCt_LhU 
As you can see it is public. If you want that changed let me know.
> Embedding video, adding PS tag definitions

- pyscriptjs/src/components/pyrepl.ts
Hi,
This PR adds type annotations to fix some ESLint warnings related to `PyRepl`.
> Add type annotations

- pyscriptjs/src/components/pybutton.ts
- pyscriptjs/src/components/pyinputbox.ts
Hi,
This PR fixes the process of adding event listeners to fix #420.
> Fix event handling issue

- pyscriptjs/src/stores.ts
Having same logging message before and after setting initializer creates some confusion and this pr fixes that!
> fixed the logging of initializers

- pyscriptjs/src/components/base.ts
- pyscriptjs/src/components/pyrepl.ts
- pyscriptjs/src/utils.ts
Minor refactorings, including
-  removing unused variables
-  condensing multi-line return logic into a single logical OR operator
-  replace if/else with ternary operator for readability
-  grouping identical logic into a function
> Minor refactoring

- pyscriptjs/examples/panel.html
- pyscriptjs/examples/panel_deckgl.html
- pyscriptjs/examples/panel_kmeans.html
- pyscriptjs/examples/panel_stream.html
- Indented python code
- Update to panel 0.13.1
- Use updated APIs to render to DOM
> Update panel examples to panel 0.13.1

- .github/workflows/sync-examples.yml
- README.md
- docs/tutorials/getting-started.md
- pyscriptjs/Makefile
Following up to #433 fixing a few left behind and clean up items.
> Fix examples Ci, Makefile, some doc references

- pyscriptjs/src/components/base.ts
- pyscriptjs/src/pyscript.py
Hey,
this PR contains some small cleanups regarding #439.
Kind regards
Mariano
> [FIX] output management cleanups

- docs/tutorials/getting-started.md
replaces #270 since docs has moved
> fix GETTING STARTED indentation

- docs/README.md
The Contributing Guidelines are referenced in the PyScript Documentation readme. Added a quick link to get there
> added a link to the Contributing Guidelines

- pyscriptjs/src/components/base.ts
- pyscriptjs/src/components/pybutton.ts
- pyscriptjs/src/components/pyinputbox.ts
> Fix extensions regression bug

- examples/altair.html
- examples/antigravity.html
- examples/d3.html
- examples/folium.html
- examples/handtrack/say_hello.html
- examples/matplotlib.html
- examples/message_passing.html
- examples/numpy_canvas_fractals.html
- examples/panel_deckgl.html
- examples/panel_kmeans.html
- examples/panel_stream.html
- examples/simple_bioinformatics_tool.html
- examples/toga/freedom.html
- examples/webgl/raycaster/index.html
I noticed `non found error` for favicon in several pages. This fixes all of them.
> Fix all favicon issues

- docs/tutorials/getting-started.md
https://github.com/pyscript/pyscript/blob/main/README.md
> Added link to Readme file

- examples/webgl/raycaster/index.html
Signed-off-by: Ryan Russell <ryanrussell@users.noreply.github.com>
> Improve WebGL Raycaster example

- .github/release.yml
- .github/workflows/build-latest.yml
- .github/workflows/build-release.yml
- .github/workflows/publish-release.yml
Adds release template, adds testing back, allows for overwriting of "latest" alpha at pyscript.net/alpha/**
> add release.yml, release automation ready for prod

- examples/index.html
This project made my day! Here are a couple of small issues I found in the index page for the examples. Amazing work and thank you for putting this out into the world!
> Fix inconsistencies and reduce verbosity in examples/index.html

- docs/tutorials/getting-started.md
As a new user that's not very experienced with programming I found the documentation to be a bit unclear, especially regarding the "getting started" section. So I made my best attempt to clear it up in a way that could be understood by people with less experience such as myself. Also there was a missing link :)
> Added section and cleared up documentation in getting started

- pyscriptjs/src/components/base.ts
- pyscriptjs/src/components/pyconfig.ts
- pyscriptjs/src/components/pyrepl.ts
- pyscriptjs/src/components/pyscript.ts
- pyscriptjs/src/stores.ts
Hi,
As the title says, this PR adds type annotations to the environments.
> Add type annotations to the environments

- pyscriptjs/Makefile
Minor PR to improve developers onboarding. Adds checks for node and npm versions and rename `example` to `examples`
> Rename examples cmd and add checks

- .github/workflows/sync-examples.yml
Examples should be synced to pyscript.net in lockstep with stable releases so that we can ensure they work.
> sync examples on stable releases

- CONTRIBUTING.md
- TROUBLESHOOTING.md
Hi, I have found dead links in docs and some typos.
Let me send this PR to fix them.
> fix links in contribution & troubleshooting doc

- pyscriptjs/src/interpreter.ts
Hi,
This PR changes to use string interpolations to improve the readability of the Python code.
> Improve with string interpolations

- pyscriptjs/package-lock.json
Initial work (please let me know if this is all I need to do), to update the version of Pyodide we're using. Fixes #629.
> Update to latest Pyodide

- pyscriptjs/src/stores.ts
Hi,
This PR removes redundant subscriptions to make the stores simple.
> Make the stores simple

- pyscriptjs/Makefile
Fixes https://github.com/pyscript/pyscript/issues/639
> change args for Linux for sed

- pyscriptjs/src/components/pyrepl.ts
> remove output manager code injection in repl source

- pyscriptjs/Makefile
Hi, this is a personal request.
I use this flow all the time and I have to change the `env` variable to `$CONDA_PREFIX` but I'd like to just run one line every time instead of running the line, forgetting I didn't modify the `Makefile` modify it and then run the tests again.
Let me know if you'd like something to change but bear in mind this is mostly a command for experienced contributors :)
> Create command to run tests locally

- pyscriptjs/src/components/pyconfig.ts
> update pyodide version

- pyscriptjs/Makefile
- pyscriptjs/src/components/base.ts
- pyscriptjs/tests/py-unit/test_pyscript.py
Close #716 
Temporarily fixes the problem generating the bug. This is really not the real solution... which is refactoring that whole workflow, which is in #622
> fix error management bug and improve examples automation

- README.md
UPDATE: Specified to add files to head tag of HTML file
> Add clarification where to place script and stylesheet - README.md

- pyscriptjs/src/components/base.ts
Hi,
This PR fixes misused promises to resolve the following ESLint error:
```console
$ npx eslint src/components/base.ts | grep no-misused-promises
200:28  error    Promise returned in function argument where a void return was expected                                                                                              @typescript-eslint/no-misused-promises
245:32  error    Promise returned in function argument where a void return was expected                                                                                              @typescript-eslint/no-misused-promises
```
Ref: https://typescript-eslint.io/rules/no-misused-promises/
> Fix misused promises

- pyscriptjs/package-lock.json
- pyscriptjs/package.json
Hi,
This PR updates TypeScript to the latest version.
> Update TypeScript to 4.8

- .github/workflows/build-unstable.yml
Sync job does not need a default working dir.
> fix ci file sync

- pyscriptjs/src/components/pyscript.ts
> pyon-dragover to py-dragover

- docs/_static/examples/what-is-pyscript.html
- docs/tutorials/getting-started.md
https://pyscript.net/alpha/ is not being updated constantly; change to https://pyscript.net/latest in READMEs and GETTINGSTARTED to match pyscript.net changes.
> change documentation to point to latest instead of frozen alpha

- pyscriptjs/src/main.ts
Ridiculous contribution to fix a typo I spotted looking at the console while testing the `unstable` version of PyScript :)
> Fixed typo in logger message

- CONTRIBUTING.md
- pyscriptjs/Makefile
This PR adds a bit more information on how to develop locally, it mentions activating the conda env so pre-commit and all the rest of the dependencies are installed and also how to install pre-commit (are you happy with this or would you rather run it manually?)
I've also removed the mention that you needed to rebase all the commits on your branch into one (it seems we are okay with multiple commits since we are squash merging? Happy to revert the change though :smile: )
closes: #770
> Update contributing docs and remove lint from makefile

- docs/howtos/http-requests.md
- docs/howtos/index.md
- docs/index.md
This PR adds a How-to on making HTTP requests from within pyscript, using pyfetch in Pyodide, which is a wrapper around the `fetch` API. (Read the PR how to if you want to learn more!) The inability to use requests/httpx is one of the first and most common questions by newcomers, hence the need.
This How-to was suggested by https://github.com/pyscript/pyscript/pull/151#issuecomment-1243714175 based on the related community example by me in #151. 
Edit: I verified the output on Sphinx autobuilt docs and on GitHub. It looks good to me!
> add pure-python (async) HTTP request how to

- examples/altair.html
- examples/antigravity.html
- examples/bokeh.html
- examples/bokeh_interactive.html
- examples/folium.html
- examples/matplotlib.html
- examples/message_passing.html
- examples/micrograd_ai.html
- examples/numpy_canvas_fractals.html
- examples/panel.html
- examples/panel_deckgl.html
- examples/panel_kmeans.html
- examples/panel_stream.html
- examples/repl.html
- examples/repl2.html
- examples/simple_clock.html
- examples/todo-pylist.html
- examples/todo.html
- examples/toga/freedom.html
All examples to `<py-config>` where `<py-env>` was in use.
> examples: py-env to py-config

- README.md
The readme.md lacked any mention of Pyodide
> Credit Pyodide within readme.md

- docs/tutorials/getting-started.md
@tedpatrick please merge this before the release :)
> update docs for the minimal config

- README.md
from Ted Patrick --
tedpatrick — 09/19/2022
Hello and Good Morning (CST in Austin TX)
Key: We want the dialog about Pyscript OSS to be transparent and centered in the community. Rather than add another communication platform, using this Discord meets the community where they are.
> Add discord channel

- docs/_static/examples/what-is-pyscript.html
- docs/tutorials/getting-started.md
- examples/altair.html
- examples/antigravity.html
- examples/bokeh.html
- examples/bokeh_interactive.html
- examples/folium.html
- examples/matplotlib.html
- examples/message_passing.html
- examples/micrograd_ai.html
- examples/numpy_canvas_fractals.html
- examples/panel.html
- examples/panel_deckgl.html
- examples/panel_kmeans.html
- examples/panel_stream.html
- examples/repl.html
- examples/repl2.html
- examples/simple_clock.html
- examples/todo-pylist.html
- examples/todo.html
- examples/toga/freedom.html
- pyscriptjs/tests/integration/test_py_config.py
Closes https://github.com/pyscript/pyscript/issues/820
> move py-config between body tags

- docs/index.md
Fixes https://github.com/pyscript/pyscript/issues/819
> remove warning in docs

- pyscriptjs/public/index.html
- Correct the url in the example
> Fix the director listing example. 

- examples/handtrack/say_hello.html
- examples/mario/play_mario.html
- pyscriptjs/package-lock.json
- pyscriptjs/package.json
- pyscriptjs/rollup.config.js
- pyscriptjs/tsconfig.json
This PR removes the last remaining of svelte 😄 
Locally the  simply_clock failed on every run, but after testing main it started passing so I'm not sure if it will fail here 🤔 
Fixes:  #883
> Remove the remains of svelte

- docs/reference/elements/py-repl.md
> Fix bug in docs

- pyscriptjs/src/pyodide.ts
- pyscriptjs/src/utils.ts
- pyscriptjs/tests/integration/support.py
- pyscriptjs/tests/integration/test_01_basic.py
This addresses https://github.com/pyscript/pyscript/issues/519
While packages are not determined automatically for now, but at least the structure is retained aka it is not flattened.
> Retain path structure for loading paths

- pyscriptjs/src/components/pybox.ts
- pyscriptjs/src/components/pybutton.ts
- pyscriptjs/src/components/pyinputbox.ts
- pyscriptjs/src/components/pyrepl.ts
- pyscriptjs/src/components/pyscript.ts
- pyscriptjs/src/components/pywidget.ts
- pyscriptjs/src/logger.ts
- pyscriptjs/src/main.ts
- pyscriptjs/src/pyconfig.ts
- pyscriptjs/src/pyexec.ts
- pyscriptjs/src/pyodide.ts
- pyscriptjs/src/runtime.ts
- pyscriptjs/src/utils.ts
Hi,
This PR just ran Prettier to format the TypeScript files.
> Format the TypeScript files

- MAINTAINERS.md
Welcome @FabioRosado as maintainer
> Add Fabio Rosado as PyScript Maintainer

- docs/reference/elements/py-config.md
Hi,
This PR adds syntax highlighting to the `<py-config>` doc.
> Add syntax highlighting

- pyscriptjs/src/components/pyrepl.ts
- pyscriptjs/tests/integration/support.py
- pyscriptjs/tests/integration/test_00_support.py
- pyscriptjs/tests/integration/test_py_repl.py
What is not tested is broken :man_facepalming: 
Test&fix `<py-repl auto-generate=true>` which was broken by PR #884
> Fix py-repl auto-generate=true

- pyscriptjs/src/pyconfig.ts
Fixes https://github.com/pyscript/pyscript/issues/925
> decode innerhtml for pyconfig

- pyscriptjs/src/plugins/fetch.ts
Use the new `UserError` paradigm by @FabioRosado
> use user error for paths calculation

- docs/reference/modules/pyscript.md
Hi,
This PR fixes a typo in the pyscript doc.
> Fix a typo

- pyscriptjs/src/pyodide.ts
- pyscriptjs/src/runtime.ts
Hi,
This PR adds the `unknown` type annotations to resolve some ESLint warnings related to the `any` type.
> Specify the `unknown` type

- pyscriptjs/src/pyodide.ts
> add docstrings for loadFromFile

- .github/workflows/docs-review.yml
- .github/workflows/docs-unstable.yml
Following Antonio's suggestion, this PR removes commented out code from our github actions to avoid us uncomment them in the future by mistake 😄
> Remove comments from github actions

- pyscriptjs/tests/integration/support.py
- pyscriptjs/tests/integration/test_00_support.py
- pyscriptjs/tests/integration/test_01_basic.py
- pyscriptjs/tests/integration/test_py_config.py
Return a 404 when a file does not exist in local disk
> Fake server 404 support

- examples/antigravity.py
- pyscriptjs/tests/integration/test_zz_examples.py
This PR fixes an issue with the antigravity example, which had started sometime since the 2022.09.1 release, and which is related to the new way of handling output.
~~This PR is a WIP.~~ This PR is ready for review.
Tasks remaining:
Fixes #1005
> Fix antigravity

- docs/reference/elements/py-config.md
Inspired by @JeffersGlass
Closes https://github.com/pyscript/pyscript/issues/1007
> updated docs for fetch

- pyscriptjs/src/runtime.ts
PR changing the final version number for 2022.12.1.RC1
> Release 2022.12.1.RC1

- docs/tutorials/py-config-fetch.md
Fixes https://github.com/pyscript/pyscript/issues/1035
> remove fetching of pyscript.py from tutorial

- pyscriptjs/src/components/pyscript.ts
- pyscriptjs/tests/integration/test_01_basic.py
Fixes https://github.com/pyscript/pyscript/issues/1038
TODO:
> getPySrc should return source code

- examples/pandas.html
This example file loads a remote CSV file into a Pandas dataframe, displays it and lets you manipulate it through a Python REPL.
Shows use of: Pandas, py-repl, py-terminal, basic DOM manipulation.
> Pandas example file for /examples folder

- examples/bokeh.html
Hellow
I've just noticed a bug(?) while fixing this. Tracked here: #1100
> we don't really use numpy here

- pyscriptjs/src/components/pyscript.ts
- pyscriptjs/src/pyexec.ts
- pyscriptjs/tests/integration/test_01_basic.py
- pyscriptjs/tests/integration/test_02_display.py
Fixes https://github.com/pyscript/pyscript/issues/1118
> fix exception thrown but not shown in DOM in event handler

- pyscriptjs/Makefile
`make test` command was incomplete.
> Missing one line to make test

- pyscriptjs/src/python/pyscript.py
> Remove @staticmethod decorator from top level definitions

- pyscriptjs/Makefile
I forgot to add this code in #1242. It generates the actual test report data.
> Actually generate test reports

- docs/reference/elements/py-script.md
Hey @JeffersGlass added description for `src` attribute as per your suggestion in #1079
> #1079 Added description of src attribute to py-script

- examples/handtrack/say_hello.html
- examples/mario/play_mario.html
Fixes syntax errors in say_hello.html and play_mario.html
> Add missing </body> tags

- .github/PULL_REQUEST_TEMPLATE.md
Added a pull request template as mentioned in the issue #1236 .
> Added Pull request template

- examples/micrograd_ai.py
- pyproject.toml
- pyscriptjs/src/python/pyscript/__init__.py
- pyscriptjs/tests/integration/conftest.py
Reverts pyscript/pyscript#1277
> Revert "Ruff: Add pylint"

- docs/changelog.md
- docs/development/developing.md
> Docs: `make tests` should be `make test`

- pyscriptjs/src/main.ts
- pyscriptjs/tests/unit/main.test.ts
- pyscriptjs/tests/unit/setup.ts
This resolves https://github.com/pyscript/pyscript/issues/1315. It is on top of https://github.com/pyscript/pyscript/pull/1318.
There isn't all that much to do here, just a couple of minor fixes.
> Fix main.test.ts

- docs/reference/API/display.md
Delete wrong code comments.
Wrong comment for describing code was probably copied from the example above it
> DOCS Update display.md

- pyscriptjs/package-lock.json
- pyscriptjs/package.json
- pyscriptjs/src/interpreter_client.ts
- pyscriptjs/src/main.ts
- pyscriptjs/src/remote_interpreter.ts
- pyscriptjs/tests/unit/pyodide.test.ts
Switch to using the new version of synclink with support for same thread syncify (and also correct types). 
Uses syncify to replace one use of `_unwrapped_remote`.
> same thread syncify

- pyscriptjs/src/components/pyscript.ts
We are currently attaching always different listeners to our nodes and that cause at least these issues:
* we cannot remove those listeners later on
* we cannot re-run the listeners initialization logic without having multiple listeners for same attribute running more than once
* we cannot actually swap at runtime the interpreter whenever we'd like to have that ability in the future
* we cannot actually run the initialization via a Mutation Observer whenever we'd like to have that ability in the future, also extremely important to have 3rd party libraries be able to use our special attributes/listeners (React, Vue, as requested already in our repo)
On top of these changes, we're using more RAM than needed because we create X locally scoped arrow functions but all we need is a single …
> Simplified events listeners attachment:

- MAINTAINERS.md
Add Andrea Giammarchi as PyScript Maintainer
> Add Andrea Giammarchi as PyScript Maintainer

- pyscriptjs/src/python/pyscript/_html.py
This MR would like to address this specific comment https://github.com/pyscript/pyscript/pull/1453#pullrequestreview-1414853366
* use a single JS <-> Python roundtrip to add or remove multiple classes
> Simplified classList within Python code

- docs/tutorials/requests.md
only closing html tag in documentation
from </html  to </html>
> html tag not closed

- pyscriptjs/src/plugin.ts
As mentioned in the related issue, we'd like to make it possible to await all plugins lifecycle at once to grant async and parallelism.
* group all JS plugins as unique `await`
* group all Python plugins as unique `await`
* preserve previous code and logic intention
> Fix #1474 - await both JS and Python plugins all at once

- .github/workflows/docs-unstable.yml
- docs/index.md
Docs - Error html to root of html
> Error html to root of docs

- docs/reference/modules/pyscript.md
Simple docs change to trigger a build
> Docs correction

- pyscriptjs/src/interpreter_client.ts
- pyscriptjs/src/main.ts
- pyscriptjs/src/plugin.ts
- pyscriptjs/tests/integration/test_plugins.py
- pyscriptjs/tests/unit/pyodide.test.ts
Closes https://github.com/pyscript/pyscript/issues/1384
> kill unwrapped_remote

- .github/workflows/build-unstable.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-release.yml
As requested, although a bit late, beefier runners to make short work of long test suites.
> Use 8-core, 32GB runners for testing and faster builds

- .github/workflows/test-next.yml
This PR will add a specific CI for next now in the right branch 😅   I considered just changing the `TestAndBuild` we have but maybe this one is okay?
@WebReflection  If this works, should we just run the next tests in CI and skip core and all others?
> Add ci for next

- .github/workflows/build-unstable.yml
- .github/workflows/docs-release.yml
- .github/workflows/docs-review.yml
- .github/workflows/docs-unstable.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/sync-examples.yml
- .github/workflows/test-next.yml
- .github/workflows/test_report.yml
- pyscriptjs/package-lock.json
- pyscriptjs/package.json
- Set to ubuntu-latest-8core
- Update ts-jest to version tested with TS 5
> Fix build unstable to run on ubuntu-latest-8core

- .github/workflows/prepare-release.yml
- .github/workflows/publish-release.yml
The steps in prepare-release and publish-release differ in steps with build-unstable. This PR makes them the same.
> Same steps as build-unstable

- pyscript.core/index.html
- pyscript.core/test/order.html
This MR adds some missing integration test to the index.html for the test folder.
* added `order` test after fixing it
* added the **input** test case
* better wording for the PyScript next link
> Better test index

- examples/webgl/raycaster/style.css
Removing commented out code
Removing commented out code
> Removing unused code

- .pre-commit-config.yaml
- pyscript.next/README.md
- pyscript.next/package-lock.json
- pyscript.next/package.json
- pyscript.next/src/core.js
- pyscript.next/tsconfig.json
- pyscript.next/types/core.d.ts
- pyscript.next/types/exceptions.d.ts
- pyscript.next/types/fetch.d.ts
This MR adds types and a basic README to allow early adopter/testers to use the module from *npm*
Added typescript to create the module export definition types
> Prepared for the first publish

- pyscript.core/LICENSE
- pyscript.core/package-lock.json
- pyscript.core/package.json
As [discussed in here](https://github.com/pyscript/pyscript/pull/1606#discussion_r1287240509), we'd like to provide the right LICENSE file for this project.
* update the LICENSE file
* update dependencies that carry similar LICENSE file
* updated the version to land latest LICENSE in *npm*
> [next] Updated LICENSE & dependencies

- LICENSE
> fix LICENSE info around dates and project owner

- pyscript.core/test/target.html
Little tweaks: adjusts the comments in the newly added/updated `target.html` document from this morning to describe the new behavior after #1673.
> Adjust Comments in `target.html` test

- pyscript.core/package-lock.json
- pyscript.core/package.json
This MR updates the *npm* module to both be sure what we publish is correct and help forward with docs and the release.
* update the module version
> [next] @pyscript/core 0.1.8

- pyscript.core/rollup/core.config.js
- pyscript.core/src/core.js
This MR adds our own copy to the final dist + it pollutes the dist folder with sourcemap related files.
* added our own team as copy on top of core.js file
* added sourcemap files to the dist folder
> [next] Add PyScript Developers Team copy

- pyscript.core/test/terminal.html
- pyscript.core/test/terminal.py
This MR simply adds a very basic terminal test page, originally created by @antocuni, with runtime code evaluation.
* added `test/termina.html`
* added `test/terminal.py`
> [next] Testing XTerm

- .github/workflows/next-build-snapshot.yml
GH Actions for building a snapshot release
- Runs on `next` branch
- Manually build to /snapshots/{name}
> Next Build Snapshot

- pyscript.core/test/terminal.py
Last push from previous MR https://github.com/pyscript/pyscript/pull/1696 didn't happen ... now it's in
* actually apply @antocuni suggestion
> [next] Terminal smoke-test follow up

- public/index.html
Add an html template for releases
- change [[PATH]] to deployed path of version
- link to files
- include a copy/paste html example
> Add release html template

- .github/workflows/next-build-snapshot.yml
When we generate a snapshot, add an html file:
- List of files in snapshot
- Simple example
- Working PyScript App
> Generate HTML for snapshot

- .github/workflows/next-build-snapshot.yml
Fix error in html template generation
> Fix sed delimiter for html generation

- public/index.html
> Fix HTML template

- .github/workflows/next-build-snapshot.yml
Fix sed command
- i option does not allow custom delimiters
- Target _PATH_ not [[PATH]]
> Fix path variable

- public/index.html
> Fix to HTML template logic

- .github/workflows/test-next.yml
- Run CI Tests for any change to `next`
> Turn on CI tests for next

- .github/workflows/test-next.yml
- Change `npm test` to `make test` on root
> Update CI tests on Next

- .github/workflows/test-next.yml
> Update tests for CI on next

- .github/workflows/test-next.yml
> Update CI tests

- .github/workflows/publish-snapshot.yml
- Restore GHAction for build snapshot
> Add publish snapshot GHA

- .github/workflows/publish-snapshot.yml
> Update publish snapshot

- .github/workflows/publish-unstable.yml
> Update Publish Unstable

- .github/workflows/publish-unstable.yml
Update path in publish-unstable
> Update pathing in publish-unstable

- .github/workflows/publish-unstable.yml
> Fix publish unstable

- .github/workflows/publish-unstable.yml
Add permissions
```
permissions:
contents: read
id-token: write
```
> Add permissions section

- .github/workflows/prepare-release.yml
- .github/workflows/publish-release.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/publish-unstable.yml
- Add prepare-release.yml
- Add publish-release.yml
> Prepare and Publish Release

- pyscript.core/package-lock.json
- pyscript.core/package.json
As usual, forgot to bump version with latest MR so now it's published with latest dependencies.
* bump patch version and publish
> Updated npm version

- README.md
Fixes #1782 
-   [X] All tests pass locally
-   [X] I have updated `docs/changelog.md`
-   [X] I have created documentation for this(if applicable)
> Fix Process link is README file #1782

- .gitignore
- pyscript.core/package.json
This MR simply addresses [this discord comment](https://discord.com/channels/972017612454232116/972020206538997822/1166281173639630898).
* added an explicit `release` build step that builds and zip the dist folder
* excluded the `dist.zip` file from GitHub
> Create a dist.zip artifact

- pyscript.core/package-lock.json
- pyscript.core/package.json
- pyscript.core/src/config.js
- pyscript.core/src/core.js
- pyscript.core/src/plugins/py-terminal.js
- pyscript.core/test/hooks.html
- pyscript.core/test/mpy.html
- pyscript.core/test/mpy.spec.js
- pyscript.core/test/py-terminal.html
- pyscript.core/tests/integration/test_py_terminal.py
- pyscript.core/types/core.d.ts
- pyscript.core/types/plugins.d.ts
- pyscript.core/types/plugins/py-terminal.d.ts
This MR brings in what agreed and discussed in https://github.com/pyscript/pyscript/pull/1801#issuecomment-1777645982
* rewrite the whole thing after new hooks landed
* improved the plugins ergonomics by awaiting these if they return a promise as default
* test via smoke test everything is fine
* the terminal is still one per page and it allows workers to have full acces while on main it's still read-only for users
> PyScript Terminal - the latest kind

- pyscript.core/package-lock.json
- pyscript.core/package.json
- pyscript.core/tsconfig.json
- pyscript.core/types/core.d.ts
- pyscript.core/types/fetch.d.ts
After dozen changes across multiple modules and various amends, it looks like correct types should be back in the project.
This MR specifically targets this comment: https://github.com/pyscript/pyscript/discussions/1838#discussioncomment-7464928
* updated coincident and polyscript (multiple times) to fix TS exports issues
* recreated TS without warnings
> Fix #1838 - Provides all TS from all projects

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
From our discord channel:
> Fabio: Where's the docs/changelog.md ?
> Jeff: Do we just want to add a top level “changelog” document, copy the old contents in, and add a section for this release?
> Nicholas: IMHO, yes we need a changelog - this is a technical "record" rather than "docs" and should probably be in the top level of the repository (i.e. adjacent to authors.txt and readme.txt etc...)
**TODO: UPDATE THE CHANGELOG FOR RELEASE.**
1. Re-add `CHANGELOG.md` from the tip of "classic" into root of the repository.
2. Tidy the formatting in `CHANGELOG.md`.
3. Update the PR template to reflect the new location of the `CHANGELOG.md`.
-   [x] I have updated `docs/changelog.md` :rofl: 
> Re-add CHANGELOG.md into root of the repository.

- pyscript.core/test/click.html
- pyscript.core/types/stdlib/pyscript.d.ts
The example had a bug that would show up when users click on the button. In summary, the id of the target div was mispelled.
Corrected the `id` of the target div
> Fix Click test example

- README.md
> Use UTC calendar in the README

- pyscript.core/package-lock.json
- pyscript.core/package.json
This MR updates dev-dependencies but most importantly polyscript built on top of latest coincident which fixes the issue we had with arrays VS objects and Object.keys or other methods.
* updated all dependencies to their latest
> Updated dev/dependencies w/ polyscript & coincident

- README.md
Simple fix for the README that also directs it to the GH pages site directly.
> Fix README.md broken link and update for GH pages docs

- CONTRIBUTING.md
- README.md
- pyscript.core/src/exceptions.js
- pyscript.core/src/hooks.js
- pyscript.sw/README.md
Swapped docs to GH Pages and need to add the `/docs/` path to a few more places to fix broken links.
> fix more docs urls

- pyscript.core/package-lock.json
- pyscript.core/package.json
- pyscript.core/src/core.css
- pyscript.core/src/plugins/py-editor.js
- pyscript.core/test/py-editor.html
This MR fixes https://github.com/pyscript/pyscript/issues/1890 because for some reason latest changes didn't go through (maybe some bad rebase from my side).
* use the latest changes from the previous MR without conflicts
* test that everything actually works as expected
> Fix #1890 - Apply latest patch that was lost

- pyscript.core/package-lock.json
- pyscript.core/package.json
- pyscript.core/src/config.js
- pyscript.core/src/core.js
- pyscript.core/test/config-url.html
- pyscript.core/test/config-url/config.json
- pyscript.core/test/config-url/src/test.py
- pyscript.core/test/mpy.spec.js
This MR fixes https://github.com/pyscript/pyscript/issues/1943
* updated polyscript to its latest
* passed along the configURL when there is one meaningful
* added integration test with both main and worker
> Fix #1943 - Updated Polyscript with configURL

- pyscript.core/package-lock.json
- pyscript.core/package.json
This MR brings in latest polyscript with updated pyodide in it.
* update dependencies
> updated Pyodide to 0.25.0

- pyscript.core/src/stdlib/pyweb/ui/shoelace.py
- pyscript.core/test/ui/examples.py
Add shoelace radio component
-   [ x] All tests pass locally
> Add shoelace radio component

- pyscript.core/src/stdlib/pyweb/ui/shoelace.py
- pyscript.core/test/ui/demo.py
- pyscript.core/test/ui/examples.py
This PR adds a bunch more elements to PyShoes:
- CopyButton
- Skeleton
- Spinner
- Switch
- Textarea
- Tag
- Range
- RelativeTime
> Add a bunch more elements

- pyscript.core/src/stdlib/pyweb/ui/shoelace.py
- pyscript.core/test/ui/examples.py
> Add radio group

- .github/ISSUE_TEMPLATE/bug-report.yml
This PR adds a section to the bug report to point users to the right repository if they are opening a bug report related to pyscript.com.
> Update bug template to point users to pyscript.com issue tracker

- README.md
Update the `README.md` to include a section about releasing PyScript.
> Add release information to README.

- CONTRIBUTING.md
* fix 2 links on CONTRIBUTING.md page
* fix #2068 
-   [-] I have created documentation for this(if applicable)
> refs #2068 fix links on CONTRIBUTING.md

- README.md
This MR reflects latest release.
* update the Calver number
> Updated reference code to grab latest

- pyscript.core/src/stdlib/pyscript/web/elements.py
> Controversial version where Element just delegates to the underlying DOM element.

- pyscript.core/package-lock.json
- pyscript.core/package.json
Turns out methods / functions attached to `window` proxy were not awaited and this was not playing well with coroutines / tasks.
```python
from pyscript import window
async def test():
print("ok")
return True
window.test = test
```
When invoked Pyodide or MicroPython would just return the task/coroutine object instead of awaiting its result (in this example, the `True` value).
> Fixed async methods attached to window

- pyscript.core/package-lock.json
- pyscript.core/package.json
- pyscript.core/rollup/stdlib.cjs
This MR fixes https://github.com/pyscript/pyscript/issues/2167 by providing visual and meaningful instructions on how to build the project.
* add a `try/catch` around the build intent
* explain what's needed to be sure the `npm run build` command won't fail again
> Fix #2167 - Provide instructions to build the project

- pyscript.core/src/stdlib/pyscript/websocket.py
This MR allows `ws` references to define after the constructor a way to read or write `onmessage` and other listeners without throwing on Pyodide.
* use `setattr` to avoid *Pyodide* issue with assigning *JS* attributes
* reflect what's been documented already as possibilities (both constructor and attributes through the reference)
> Make WebSocket lazy attributes definition possible

- core/package-lock.json
- core/package.json
- core/src/plugins/py-editor.js
- core/tests/manual/py-editor-failure.html
- core/tests/manual/py-editor.html
- core/types/core.d.ts
This MR goal is to fix https://github.com/pyscript/pyscript/discussions/2215 by providing a way, for advanced users, to terminate a worker once an editor has been removed from the DOM.
* lazily expose the `xworker` once created
* test manually that everything works as expected
> Provide an xworker to PyEditors

- Makefile
Ensure precommit check is done before each build when using make.
Minor update to Makefile
-   [ ] I have checked `make build` works locally.
> Ensure precommit check is done before each build when using make.

- core/package-lock.json
- core/package.json
- core/tests/manual/game/aliens.py
This MR is simply to push the latest 2024 version of PyScript in here or *npm*.
* update all dev/dependencies
* tested everything worked as expected
> Latest 2024

- README.md
This MR simply bumps the latest version in the README
> Bumped version to 2025.8.1

- core/package-lock.json
- core/package.json
Latest MicroPython preview 256 is now in.
* updated Polyscript
> Amend on MicroPython latest
